GO

IF COLUMNPROPERTY(OBJECT_ID('dbo.UMS_CLAIM'), 'IsDeleted', 'ColumnId') IS NULL
BEGIN 
ALTER TABLE UMS_CLAIM
	ADD IsDeleted bit NULL
	Print('UMS_CLAIM.IsDeleted Added')
END
GO
UPDATE UMS_CLAIM SET IsDeleted = 0 WHERE IsDeleted IS NULL
GO
ALTER TABLE UMS_CLAIM
	ALTER COLUMN IsDeleted bit NOT NULL
GO


IF COLUMNPROPERTY(OBJECT_ID('dbo.LDS_DOCUMENT_COMMENTS'), 'Comment', 'ColumnId') IS NOT NULL
BEGIN 
ALTER TABLE LDS_DOCUMENT_COMMENTS ALTER COLUMN Comment NVARCHAR(100) NULL
	Print('LDS_DOCUMENT_COMMENTS.Comment Altered')
END