IF COLUMNPROPERTY(OBJECT_ID('dbo.ATTACHMENT_TYPE'), 'IsMandatory', 'ColumnId') IS NULL
BEGIN 
ALTER TABLE ATTACHMENT_TYPE
	ADD IsMandatory bit NOT NULL default 0
	Print('ATTACHMENT_TYPE.IsMandatory Added')
END

IF COLUMNPROPERTY(OBJECT_ID('dbo.TEMP_ATTACHEMENTS'), 'OtherAttachmentType', 'ColumnId') IS NULL
BEGIN 
ALTER TABLE TEMP_ATTACHEMENTS
	 ADD OtherAttachmentType NVARCHAR(500)
	Print('TEMP_ATTACHEMENTS.OtherAttachmentType Added')
END

IF COLUMNPROPERTY(OBJECT_ID('dbo.TEMP_ATTACHEMENTS'), 'Description', 'ColumnId') IS NULL
BEGIN 
ALTER TABLE TEMP_ATTACHEMENTS
	 ADD Description NVARCHAR(MAX)
	Print('TEMP_ATTACHEMENTS.Description Added')
END

IF COLUMNPROPERTY(OBJECT_ID('dbo.TEMP_ATTACHEMENTS'), 'ReferenceNo', 'ColumnId') IS NULL
BEGIN 
ALTER TABLE TEMP_ATTACHEMENTS
	 ADD ReferenceNo NVARCHAR(50)
	Print('TEMP_ATTACHEMENTS.ReferenceNo Added')
END

IF COLUMNPROPERTY(OBJECT_ID('dbo.TEMP_ATTACHEMENTS'), 'ReferenceDate', 'ColumnId') IS NULL
BEGIN 
ALTER TABLE TEMP_ATTACHEMENTS
	 ADD ReferenceDate Date
	Print('TEMP_ATTACHEMENTS.ReferenceDate Added')
END

IF COLUMNPROPERTY(OBJECT_ID('dbo.TEMP_ATTACHEMENTS'), 'DocumentDate', 'ColumnId') IS NULL
BEGIN 
ALTER TABLE TEMP_ATTACHEMENTS
	 ADD DocumentDate Date
	Print('TEMP_ATTACHEMENTS.DocumentDate Added')
END


sp_rename 'dbo.LMS_LITERATURE_UPLOADED_DOCUMENT', 'UPLOADED_DOCUMENT'
--UPLOADED_DOCUMENT
IF COLUMNPROPERTY(OBJECT_ID('dbo.UPLOADED_DOCUMENT'), 'Description_En', 'ColumnId') IS NULL
BEGIN 
ALTER TABLE UPLOADED_DOCUMENT DROP COLUMN Description_En
	Print('UPLOADED_DOCUMENT.Description_En Dropped')
END

IF COLUMNPROPERTY(OBJECT_ID('dbo.UPLOADED_DOCUMENT'), 'ReferenceNo', 'ColumnId') IS NULL
BEGIN 
ALTER TABLE UPLOADED_DOCUMENT
	 ADD ReferenceNo NVARCHAR(50)
	Print('UPLOADED_DOCUMENT.ReferenceNo Added')
END

IF COLUMNPROPERTY(OBJECT_ID('dbo.UPLOADED_DOCUMENT'), 'ReferenceDate', 'ColumnId') IS NULL
BEGIN 
ALTER TABLE UPLOADED_DOCUMENT
	 ADD ReferenceDate Date
	Print('UPLOADED_DOCUMENT.ReferenceDate Added')
END

IF COLUMNPROPERTY(OBJECT_ID('dbo.UPLOADED_DOCUMENT'), 'OtherAttachmentType', 'ColumnId') IS NULL
BEGIN 
ALTER TABLE UPLOADED_DOCUMENT
	 ADD OtherAttachmentType NVARCHAR(500)
	Print('UPLOADED_DOCUMENT.OtherAttachmentType Added')
END

 
IF COLUMNPROPERTY(OBJECT_ID('dbo.UPLOADED_DOCUMENT'), 'Description_Ar', 'ColumnId') IS NOT NULL
BEGIN
EXEC sp_rename 'UPLOADED_DOCUMENT.Description_Ar', 'Description', 'COLUMN' 
    Print '[dbo].[UPLOADED_DOCUMENT.Description_Ar] Renamed Successfully'
END
GO

IF COLUMNPROPERTY(OBJECT_ID('dbo.UPLOADED_DOCUMENT'), 'DocDateTime', 'ColumnId') IS NOT NULL
BEGIN
EXEC sp_rename 'UPLOADED_DOCUMENT.DocDateTime', 'DocumentDate', 'COLUMN' 
    Print '[dbo].[UPLOADED_DOCUMENT.DocDateTime] Renamed Successfully'
END
GO

IF COLUMNPROPERTY(OBJECT_ID('dbo.UPLOADED_DOCUMENT'), 'DocumentDate', 'ColumnId') IS NOT NULL
BEGIN
	ALTER TABLE UPLOADED_DOCUMENT ALTER COLUMN DocumentDate Date
    Print '[dbo].[UPLOADED_DOCUMENT.DocumentDate] Altered Successfully'
END
GO
