
/****** Object:  Table [dbo].[CMS_CASE_FILE]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_CASE_FILE](
	[FileId] [uniqueidentifier] NOT NULL,
	[RequestId] [uniqueidentifier] NOT NULL,
	[FileNumber] [nvarchar](1000) NOT NULL,
	[StatusId] [int] NOT NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](256) NULL,
	[ModifiedDate] [datetime] NULL,
	[DeletedBy] [nvarchar](256) NULL,
	[DeletedDate] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[FileId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_CASE_FILE_STATUS_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_CASE_FILE_STATUS_G2G_LKP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name_En] [nvarchar](100) NOT NULL,
	[Name_Ar] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_CASE_PARTY_CATEGORY_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_CASE_PARTY_CATEGORY_G2G_LKP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name_En] [nvarchar](500) NOT NULL,
	[Name_Ar] [nvarchar](500) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](256) NULL,
	[ModifiedDate] [datetime] NULL,
	[DeletedBy] [nvarchar](256) NULL,
	[DeletedDate] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_CASE_PARTY_LINK]    Script Date: 26/10/2022 9:33:54 am ******/
DROP TABLE [CMS_CASE_PARTY_LINK]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_CASE_PARTY_LINK](
	[Id] [uniqueidentifier] NOT NULL,
	[RequestId] [uniqueidentifier] NOT NULL,
	[CategoryId] [int] NOT NULL,
	[TypeId] [int] NOT NULL,
	[Name] [nvarchar](500) NULL,
	[CivilId] [nvarchar](20) NULL,
	[CRN] [nvarchar](30) NULL,
	[MinistryId] [int] NULL,
	[Representative] [nvarchar](500) NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](256) NULL,
	[ModifiedDate] [datetime] NULL,
	[DeletedBy] [nvarchar](256) NULL,
	[DeletedDate] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_CASE_PARTY_TYPE_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_CASE_PARTY_TYPE_G2G_LKP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name_En] [nvarchar](500) NOT NULL,
	[Name_Ar] [nvarchar](500) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](256) NULL,
	[ModifiedDate] [datetime] NULL,
	[DeletedBy] [nvarchar](256) NULL,
	[DeletedDate] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_CASE_REQUEST]    Script Date: 26/10/2022 9:33:54 am ******/
DROP TABLE [CMS_CASE_REQUEST]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_CASE_REQUEST](
	[RequestId] [uniqueidentifier] NOT NULL,
	[RequestNumber] [int] NOT NULL,
	[RequestDate] [datetime] NOT NULL,
	[ClaimAmount] [decimal](10, 2) NULL,
	[ReferenceNo] [nvarchar](50) NULL,
	[ReferenceDate] [date] NULL,
	[Remarks] [nvarchar](max) NULL,
	[CaseRequirements] [nvarchar](max) NULL,
	[Subject] [nvarchar](1000) NULL,
	[IsConfidential] [bit] NULL,
	[GovtEntityId] [int] NULL,
	[DepartmentId] [int] NULL,
	[SectorTypeId] [int] NULL,
	[SubTypeId] [int] NULL,
	[PriorityId] [int] NULL,
	[StatusId] [int] NOT NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](256) NULL,
	[ModifiedDate] [datetime] NULL,
	[DeletedBy] [nvarchar](256) NULL,
	[DeletedDate] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RequestId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_CASE_REQUEST_EVENT_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_CASE_REQUEST_EVENT_G2G_LKP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name_En] [nvarchar](500) NOT NULL,
	[Name_Ar] [nvarchar](500) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_CASE_REQUEST_STATUS_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_CASE_REQUEST_STATUS_G2G_LKP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name_En] [nvarchar](100) NOT NULL,
	[Name_Ar] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_CASE_REQUEST_STATUS_HISTORY]    Script Date: 26/10/2022 9:33:54 am ******/
DROP TABLE [CMS_CASE_REQUEST_STATUS_HISTORY]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_CASE_REQUEST_STATUS_HISTORY](
	[HistoryId] [uniqueidentifier] NOT NULL,
	[EventId] [int] NOT NULL,
	[Remarks] [nvarchar](max) NULL,
	[StatusId] [int] NOT NULL,
	[RequestId] [uniqueidentifier] NOT NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](256) NULL,
	[ModifiedDate] [datetime] NULL,
	[DeletedBy] [nvarchar](256) NULL,
	[DeletedDate] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_CMS_CASE_REQUEST_STATUS_HISTORY] PRIMARY KEY CLUSTERED 
(
	[HistoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_CHAMBER_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_CHAMBER_G2G_LKP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Number] [nvarchar](1000) NOT NULL,
	[Name_En] [nvarchar](500) NOT NULL,
	[Name_Ar] [nvarchar](500) NOT NULL,
	[Address] [nvarchar](1000) NULL,
	[CourtId] [int] NULL,
	[IsActive] [bit] NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](256) NULL,
	[ModifiedDate] [datetime] NULL,
	[DeletedBy] [nvarchar](256) NULL,
	[DeletedDate] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_COURT_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_COURT_G2G_LKP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Number] [nvarchar](1000) NOT NULL,
	[Name_En] [nvarchar](500) NOT NULL,
	[Name_Ar] [nvarchar](500) NOT NULL,
	[District] [nvarchar](500) NULL,
	[Location] [nvarchar](500) NULL,
	[TypeId] [int] NULL,
	[IsActive] [bit] NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](256) NULL,
	[ModifiedDate] [datetime] NULL,
	[DeletedBy] [nvarchar](256) NULL,
	[DeletedDate] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_COURT_TYPE_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_COURT_TYPE_G2G_LKP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name_En] [nvarchar](500) NOT NULL,
	[Name_Ar] [nvarchar](500) NOT NULL,
	[IsActive] [bit] NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](256) NULL,
	[ModifiedDate] [datetime] NULL,
	[DeletedBy] [nvarchar](256) NULL,
	[DeletedDate] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[CMS_GOVERNMENT_ENTITY_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SP_RENAME 'dbo.GOVERNMENT_ENTITY', 'CMS_GOVERNMENT_ENTITY_G2G_LKP'
/****** Object:  Table [dbo].[CMS_MINISTRY_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_MINISTRY_G2G_LKP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name_En] [nvarchar](500) NOT NULL,
	[Name_Ar] [nvarchar](500) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](256) NULL,
	[ModifiedDate] [datetime] NULL,
	[DeletedBy] [nvarchar](256) NULL,
	[DeletedDate] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_OPERATING_SECTOR_TYPE_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_OPERATING_SECTOR_TYPE_G2G_LKP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Code] [nvarchar](100) NULL,
	[Name_En] [nvarchar](500) NOT NULL,
	[Name_Ar] [nvarchar](500) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](256) NULL,
	[ModifiedDate] [datetime] NULL,
	[DeletedBy] [nvarchar](256) NULL,
	[DeletedDate] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_PRIORITY_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_PRIORITY_G2G_LKP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name_En] [nvarchar](100) NOT NULL,
	[Name_Ar] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_REGISTERED_CASE]    Script Date: 26/10/2022 9:33:54 am ******/
drop table [CMS_REGISTERED_CASE]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_REGISTERED_CASE](
	[CaseId] [uniqueidentifier] NOT NULL,
	[FileId] [uniqueidentifier] NOT NULL,
	[CANNumber] [nvarchar](1000) NOT NULL,
	[CaseNumber] [nvarchar](1000) NOT NULL,
	[CaseDate] [date] NULL,
	[CourtId] [int] NULL,
	[ChamberId] [int] NULL,
	[StatusId] [int] NOT NULL,
	[IsConfidential] [bit] NULL,
	[GovtEntityId] [int] NULL,
	[CaseRequirements] [nvarchar](max) NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](256) NULL,
	[ModifiedDate] [datetime] NULL,
	[DeletedBy] [nvarchar](256) NULL,
	[DeletedDate] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CaseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_REGISTERED_CASE_EVENT_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_REGISTERED_CASE_EVENT_G2G_LKP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name_En] [varchar](500) NOT NULL,
	[Name_Ar] [varchar](500) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_REGISTERED_CASE_STATUS_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_REGISTERED_CASE_STATUS_G2G_LKP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name_En] [nvarchar](100) NOT NULL,
	[Name_Ar] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_REGISTERED_CASE_STATUS_HISTORY]    Script Date: 26/10/2022 9:33:54 am ******/
drop table [CMS_REGISTERED_CASE_STATUS_HISTORY]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_REGISTERED_CASE_STATUS_HISTORY](
	[HistoryId] [uniqueidentifier] NOT NULL,
	[EventId] [int] NOT NULL,
	[Remarks] [nvarchar](max) NULL,
	[StatusId] [int] NOT NULL,
	[CaseId] [uniqueidentifier] NOT NULL,
	[FileId] [uniqueidentifier] NOT NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](256) NULL,
	[ModifiedDate] [datetime] NULL,
	[DeletedBy] [nvarchar](256) NULL,
	[DeletedDate] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[HistoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_SUBTYPE_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_SUBTYPE_G2G_LKP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SectorTypeId] [int] NULL,
	[Code] [nvarchar](100) NULL,
	[Name_En] [nvarchar](500) NOT NULL,
	[Name_Ar] [nvarchar](500) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](256) NULL,
	[ModifiedDate] [datetime] NULL,
	[DeletedBy] [nvarchar](256) NULL,
	[DeletedDate] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_WITHDRAW_REQUEST]    Script Date: 26/10/2022 9:33:54 am ******/

drop table [CMS_WITHDRAW_REQUEST]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_WITHDRAW_REQUEST](
	[Id] [uniqueidentifier] NOT NULL,
	[Reason] [nvarchar](max) NULL,
	[RequestNumber] [int] NOT NULL,
	[RequestDate] [datetime] NOT NULL,
	[CaseRequestId] [uniqueidentifier] NOT NULL,
	[StatusId] [int] NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](256) NULL,
	[ModifiedDate] [datetime] NULL,
	[DeletedBy] [nvarchar](256) NULL,
	[DeletedDate] [datetime] NULL,
	[IsDeleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMS_WITHDRAW_REQUEST_STATUS_G2G_LKP]    Script Date: 26/10/2022 9:33:54 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_WITHDRAW_REQUEST_STATUS_G2G_LKP](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name_En] [nvarchar](500) NOT NULL,
	[Name_Ar] [nvarchar](500) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CMS_CASE_FILE]  WITH CHECK ADD  CONSTRAINT [CMS_CASE_FILE_REQUEST] FOREIGN KEY([RequestId])
REFERENCES [dbo].[CMS_CASE_REQUEST] ([RequestId])
GO
ALTER TABLE [dbo].[CMS_CASE_FILE] CHECK CONSTRAINT [CMS_CASE_FILE_REQUEST]
GO
ALTER TABLE [dbo].[CMS_CASE_FILE]  WITH CHECK ADD  CONSTRAINT [CMS_CASE_FILE_STATUS] FOREIGN KEY([StatusId])
REFERENCES [dbo].[CMS_CASE_FILE_STATUS_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_CASE_FILE] CHECK CONSTRAINT [CMS_CASE_FILE_STATUS]
GO
ALTER TABLE [dbo].[CMS_CASE_PARTY_LINK]  WITH CHECK ADD  CONSTRAINT [CMS_CASE_PARTY_LINK_MINISTRY] FOREIGN KEY([MinistryId])
REFERENCES [dbo].[CMS_MINISTRY_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_CASE_PARTY_LINK] CHECK CONSTRAINT [CMS_CASE_PARTY_LINK_MINISTRY]
GO
ALTER TABLE [dbo].[CMS_CASE_PARTY_LINK]  WITH CHECK ADD  CONSTRAINT [CMS_CASE_PARTY_LINK_PARTY_CATEGORY] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[CMS_CASE_PARTY_CATEGORY_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_CASE_PARTY_LINK] CHECK CONSTRAINT [CMS_CASE_PARTY_LINK_PARTY_CATEGORY]
GO
ALTER TABLE [dbo].[CMS_CASE_PARTY_LINK]  WITH CHECK ADD  CONSTRAINT [CMS_CASE_PARTY_LINK_PARTY_TYPE] FOREIGN KEY([TypeId])
REFERENCES [dbo].[CMS_CASE_PARTY_TYPE_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_CASE_PARTY_LINK] CHECK CONSTRAINT [CMS_CASE_PARTY_LINK_PARTY_TYPE]
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST]  WITH CHECK ADD  CONSTRAINT [CMS_CASE_REQUEST_DEPARTMENT] FOREIGN KEY([DepartmentId])
REFERENCES [dbo].[DEPARTMENT] ([Id])
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST] CHECK CONSTRAINT [CMS_CASE_REQUEST_DEPARTMENT]
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST]  WITH CHECK ADD  CONSTRAINT [CMS_CASE_REQUEST_GOVT_ENTITY] FOREIGN KEY([GovtEntityId])
REFERENCES [dbo].[CMS_GOVERNMENT_ENTITY_G2G_LKP] ([EntityId])
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST] CHECK CONSTRAINT [CMS_CASE_REQUEST_GOVT_ENTITY]
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST]  WITH CHECK ADD  CONSTRAINT [CMS_CASE_REQUEST_PRIORITY] FOREIGN KEY([PriorityId])
REFERENCES [dbo].[CMS_PRIORITY_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST] CHECK CONSTRAINT [CMS_CASE_REQUEST_PRIORITY]
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST]  WITH CHECK ADD  CONSTRAINT [CMS_CASE_REQUEST_SECTOR_TYPE] FOREIGN KEY([SectorTypeId])
REFERENCES [dbo].[CMS_OPERATING_SECTOR_TYPE_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST] CHECK CONSTRAINT [CMS_CASE_REQUEST_SECTOR_TYPE]
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST]  WITH CHECK ADD  CONSTRAINT [CMS_CASE_REQUEST_STATUS] FOREIGN KEY([StatusId])
REFERENCES [dbo].[CMS_CASE_REQUEST_STATUS_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST] CHECK CONSTRAINT [CMS_CASE_REQUEST_STATUS]
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST]  WITH CHECK ADD  CONSTRAINT [CMS_CASE_REQUEST_SUBTYPE] FOREIGN KEY([SubTypeId])
REFERENCES [dbo].[CMS_SUBTYPE_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST] CHECK CONSTRAINT [CMS_CASE_REQUEST_SUBTYPE]
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST_STATUS_HISTORY]  WITH CHECK ADD  CONSTRAINT [CMS_CASE_HISTORY_CASE_REQUEST_STATUS] FOREIGN KEY([StatusId])
REFERENCES [dbo].[CMS_CASE_REQUEST_STATUS_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST_STATUS_HISTORY] CHECK CONSTRAINT [CMS_CASE_HISTORY_CASE_REQUEST_STATUS]
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST_STATUS_HISTORY]  WITH CHECK ADD  CONSTRAINT [CMS_CASE_HISTORY_EVENT] FOREIGN KEY([EventId])
REFERENCES [dbo].[CMS_CASE_REQUEST_EVENT_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST_STATUS_HISTORY] CHECK CONSTRAINT [CMS_CASE_HISTORY_EVENT]
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST_STATUS_HISTORY]  WITH CHECK ADD  CONSTRAINT [CMS_CASE_STATUS_HISTORY_CASE_REQUEST] FOREIGN KEY([RequestId])
REFERENCES [dbo].[CMS_CASE_REQUEST] ([RequestId])
GO
ALTER TABLE [dbo].[CMS_CASE_REQUEST_STATUS_HISTORY] CHECK CONSTRAINT [CMS_CASE_STATUS_HISTORY_CASE_REQUEST]
GO
ALTER TABLE [dbo].[CMS_CHAMBER_G2G_LKP]  WITH CHECK ADD  CONSTRAINT [CMS_CHAMBER_COURT] FOREIGN KEY([CourtId])
REFERENCES [dbo].[CMS_COURT_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_CHAMBER_G2G_LKP] CHECK CONSTRAINT [CMS_CHAMBER_COURT]
GO
ALTER TABLE [dbo].[CMS_COURT_G2G_LKP]  WITH CHECK ADD  CONSTRAINT [CMS_COURT_COURT_TYPE] FOREIGN KEY([TypeId])
REFERENCES [dbo].[CMS_COURT_TYPE_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_COURT_G2G_LKP] CHECK CONSTRAINT [CMS_COURT_COURT_TYPE]
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE]  WITH CHECK ADD  CONSTRAINT [CMS_REGISTERED_CASE_CHAMBER] FOREIGN KEY([ChamberId])
REFERENCES [dbo].[CMS_CHAMBER_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE] CHECK CONSTRAINT [CMS_REGISTERED_CASE_CHAMBER]
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE]  WITH CHECK ADD  CONSTRAINT [CMS_REGISTERED_CASE_COURT] FOREIGN KEY([CourtId])
REFERENCES [dbo].[CMS_COURT_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE] CHECK CONSTRAINT [CMS_REGISTERED_CASE_COURT]
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE]  WITH CHECK ADD  CONSTRAINT [CMS_REGISTERED_CASE_FILE] FOREIGN KEY([FileId])
REFERENCES [dbo].[CMS_CASE_FILE] ([FileId])
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE] CHECK CONSTRAINT [CMS_REGISTERED_CASE_FILE]
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE]  WITH CHECK ADD  CONSTRAINT [CMS_REGISTERED_CASE_GOVT_ENTITY] FOREIGN KEY([GovtEntityId])
REFERENCES [dbo].[CMS_GOVERNMENT_ENTITY_G2G_LKP] ([EntityId])
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE] CHECK CONSTRAINT [CMS_REGISTERED_CASE_GOVT_ENTITY]
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE]  WITH CHECK ADD  CONSTRAINT [CMS_REGISTERED_CASE_STATUS] FOREIGN KEY([StatusId])
REFERENCES [dbo].[CMS_REGISTERED_CASE_STATUS_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE] CHECK CONSTRAINT [CMS_REGISTERED_CASE_STATUS]
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE_STATUS_HISTORY]  WITH CHECK ADD  CONSTRAINT [CMS_REGISTERED_CASE_STATUS_HISTORY_CASE_EVENT] FOREIGN KEY([EventId])
REFERENCES [dbo].[CMS_REGISTERED_CASE_EVENT_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE_STATUS_HISTORY] CHECK CONSTRAINT [CMS_REGISTERED_CASE_STATUS_HISTORY_CASE_EVENT]
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE_STATUS_HISTORY]  WITH CHECK ADD  CONSTRAINT [CMS_REGISTERED_CASE_STATUS_HISTORY_CASE_FILE] FOREIGN KEY([FileId])
REFERENCES [dbo].[CMS_CASE_FILE] ([FileId])
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE_STATUS_HISTORY] CHECK CONSTRAINT [CMS_REGISTERED_CASE_STATUS_HISTORY_CASE_FILE]
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE_STATUS_HISTORY]  WITH CHECK ADD  CONSTRAINT [CMS_REGISTERED_CASE_STATUS_HISTORY_CASE_STATUS] FOREIGN KEY([StatusId])
REFERENCES [dbo].[CMS_REGISTERED_CASE_STATUS_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE_STATUS_HISTORY] CHECK CONSTRAINT [CMS_REGISTERED_CASE_STATUS_HISTORY_CASE_STATUS]
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE_STATUS_HISTORY]  WITH CHECK ADD  CONSTRAINT [CMS_REGISTERED_CASE_STATUS_HISTORY_CMS_REGISTERED_CASE] FOREIGN KEY([CaseId])
REFERENCES [dbo].[CMS_REGISTERED_CASE] ([CaseId])
GO
ALTER TABLE [dbo].[CMS_REGISTERED_CASE_STATUS_HISTORY] CHECK CONSTRAINT [CMS_REGISTERED_CASE_STATUS_HISTORY_CMS_REGISTERED_CASE]
GO
ALTER TABLE [dbo].[CMS_WITHDRAW_REQUEST]  WITH CHECK ADD  CONSTRAINT [CMS_WITHDRAW_CASE_REQUEST] FOREIGN KEY([CaseRequestId])
REFERENCES [dbo].[CMS_CASE_REQUEST] ([RequestId])
GO
ALTER TABLE [dbo].[CMS_WITHDRAW_REQUEST] CHECK CONSTRAINT [CMS_WITHDRAW_CASE_REQUEST]
GO
ALTER TABLE [dbo].[CMS_WITHDRAW_REQUEST]  WITH CHECK ADD  CONSTRAINT [CMS_WITHDRAW_STATUS_REQUEST] FOREIGN KEY([StatusId])
REFERENCES [dbo].[CMS_WITHDRAW_REQUEST_STATUS_G2G_LKP] ([Id])
GO
ALTER TABLE [dbo].[CMS_WITHDRAW_REQUEST] CHECK CONSTRAINT [CMS_WITHDRAW_STATUS_REQUEST]
GO