namespace FATWA_DOMAIN.Enums
{
    public class WorkflowModuleAndActivitiesEnum
    {
        public enum WorkflowModuleEnum
        {
            LDSDocument = 1,
            LPSPrinciple = 2,
            LMSLiterature = 3,
            UMS = 4,
            CaseManagement = 5,
            Communication = 6,
            Meeting = 7,
            MeetingMom = 8,
            Task = 9,
            COMSConsultationManagement = 10,
            CNTContactManagement = 11,
            DMS = 12,
            BugReporting = 13,
            TimeIntervalWorkerService = 14,
            NumberPatternWorkerService = 15,
            InventoryManagement = 16,
            VendorContract = 17,
            ServiceRequest = 18,
            OrganizingCommittee = 19,
            LeaveAndAttendance = 20,
            ArchivedCases = 25,

        }
        public enum WorkflowSubModuleEnum
        {
            Administrative = 1,
            CivilCommercial = 2,
            Contracts = 3,
            AdministrativeComplaints = 4,
            LegalAdvice = 5,
            Legislations = 6,
            InternationalArbitration = 7,
            LegalLegislations = 9,
            LegalPrinciples = 10,
        }
        public enum MainWorkflowModuleEnum
        {
            CaseManagement = 5,
            ConsultationManagement = 10,
            LegalLibrarySystem = 1,
            //OperationalSupportSystem = 2,
            //BugReporting = 3,
        }
        public enum WorkflowModuleTriggerEnum
        {
            UserSubmitsDocument = 1,
            UserUnpublishedDocument = 2,
            UserSubmitsPrinciple = 3,
            UserSubmitsCaseDraft = 4,
            UserSubmitsConsultationDraft = 5,
            UserSubmitsDMSDocument = 6,
            TransferCaseRequest = 7,
            TransferCaseFile = 8,
            TransferConsultationRequest = 9,
            TransferConsultationFile = 10,
            TransferConfidentialCaseRequest = 11,
            TransferConfidentialCaseFile = 12,
            TransferConfidentialConsultationRequest = 13,
            TransferConfidentialConsultationFile = 14,
            SendCopyCaseRequest = 15,
            SendCopyCaseFile = 16,
            TransferConfidentialCaseRequestPrivateOffice = 17,
            TransferConfidentialConsultationRequestPrivateOffice = 18,
        }

        public enum WorkflowActivityEnum
        {
            LdsReview = 1,
            LdsPublishUnpublish = 2,
            SendEmail = 5,
            LpsReview = 6,
            LpsPublishUnpublish = 7,
            CmsReviewDraftDocument = 8,
            CmsReviewDraftDocumentHOS = 9,
            ComsReviewDraftDocument = 10,
            ComsReviewDraftDocumentHOS = 11,
            LpsDMSReview = 12,
            CmsSendToMessengerMOJ = 13,
            CmsReviewDraftDocumentGS = 14,
            CmsReviewDraftDocumentPOO = 15,
            CmsReviewDraftDocumentLawyer = 16,
            LpsDMSPublish = 17,
            CmsTransferToSector = 18,
            CmsTransferToIntiator = 19,
            CmsSendToGS = 20,
            CmsSendToPOO = 21,
            CmsSendToPOS = 22,
            CmsTransferToPOButSendToFPForDecision = 23,
            CmsTransferToInitiatorAndEndflow = 24,
            CmsTransferToRecieverAndEndflow = 25,
            CmsApproveAndWork = 26,
            LawyerDraftModification = 27,
            PublishDraftandEndFlow = 28,
            SignDraftPublishDraftSendtoG2GandEndFlow = 29,
            CmsSendCopyToInitiator = 30,
            CmsSendCopyToGS = 31,
            CmsApproveCopyAndWork = 32,
            CmsSendCopyToInitiatorAndEndflow = 33,
            CmsSendCopyToRecieverAndEndflow = 34,
            CmsSendCopyToSector = 35,
            CmsTransferToPOAndEndFlow = 36,
            InitiatorDocumentModification = 37,
            TransferToRespectiveSectorAndEndflow = 38,
            CmsReviewDraftDocumentViceHOS = 39,
            SignDraftPublishDraftandEndFlow = 40,
        }

        public enum WorkflowConditionEnum
        {
            LdsStatusDraft,
            LdsStatusInReview,
            LdsStatusApprove,
            LdsStatusReject,
            LdsStatusNeedToModify,
            LdsStatusSendaComment,
            LdsStatusPublish,
            LdsStatusUnpublish,
            LpsStatusDraft,
            LpsStatusInReview,
            LpsStatusApprove,
            LpsStatusReject,
            LpsStatusNeedToModify,
            LpsStatusSendaComment,
            LpsStatusPublish,
            LpsStatusUnpublish,
            LpsDmsStatusDraft,
            LpsDmsStatusInReview,
            LpsDmsStatusReject,
            LpsDmsStatusApprove,
            LpsDmsStatusPublish,
            CmsSubmittedByLawyer,
            CmsSubmittedByViceHOS,
            CmsSubmittedByHOS,
            CmsDraftDocumentStatusInReview,
            CmsDraftDocumentStatusDraft,
            CmsDraftDocumentStatusReject,
            CmsDraftDocumentStatusApprove,
            CmsDraftDocumentStatusPublished,
            ComsSubmittedByLawyer,
            ComsSubmittedByViceHOS,
            ComsSubmittedByHOS,
            CmsDraftDocumentStatusApproveAndViceHOSApprovalEnough,
            CmsSubmittedByViceHOSAndViceHOSApprovalEnough,

        }
    }
}
