namespace FATWA_DOMAIN.Enums
{
    public class WorkflowParameterEnums
    {
        public enum WorkflowParams
        {
            LdsReview_User = 1,
            SendEmail_Email = 2,
            LdsPublishUnpublish_User = 3,
            LdsReview_UserRole = 4,
            LdsPublishUnpublish_UserRole = 5,
            Sla_UserRole = 6,
            Sla_Email = 7,
            LpsReview_User = 8,
            LpsReview_UserRole = 9,
            LpsPublishUnpublish_User = 10,
            LpsPublishUnpublish_UserRole = 11,
            SendEmail_Subject = 12,
            SendEmail_Body = 13,
            CmsReviewDraftDocument_User = 14,
            CmsReviewDraftDocument_UserRole = 15,
            CmsReviewDraftDocumentHos_User = 16,
            CmsReviewDraftDocumentHos_UserRole = 17,
            ComsReviewDraftDocument_User = 18,
            ComsReviewDraftDocument_UserRole = 19,
            ComsReviewDraftDocumentHos_User = 20,
            ComsReviewDraftDocumentHos_UserRole = 21,
            DMSDocumentReview_User = 22,
            DMSDocumentReview_UserRole = 23,
            CmsReviewDraftDocumentGS_User = 24,
            CmsReviewDraftDocumentGS_UserRole = 25,
            CmsReviewDraftDocumentPOO_User = 26,
            CmsReviewDraftDocumentPOO_UserRole = 27,
            CmsReviewDraftDocumentLawyer_User = 28,
            CmsReviewDraftDocumentLawyer_UserRole = 29,
            DMSDocumentPublish_User = 30,
            DMSDocumentPublish_UserRole = 31,
            CmsTransferUser = 32,
            CmsTransferUserRole = 33,
            CmsTransferToInitiatorUser = 34,
            CmsTransferToInitiatorUserRole = 35,
            CmsSendToGSUser = 36,
            CmsSendToGSUserRole = 37,
            CmsSendToPOOUser = 38,
            CmsSendToPOOUserRole = 39,
            CmsSendToPOSUser = 40,
            CmsSendToPOSUserRole = 41,
            CmsSendToFPUser = 42,
            CmsSendToFPUserRole = 43,
            CmsTransferToInitiatorAndEndflowUser = 44,
            CmsTransferToRecieverAndEndflowUser = 45,
            CmsApproveTransferAndWorkUser = 46,
            LawModifyDraftDocument_User = 47,
            LawModifyDraftDocument_UserRole = 48,
            PublishDraftandEndFlow_User = 49,
            PublishDraftandEndFlow_UserRole = 50,
            SignDraftPublishDraftSendtoG2GandEndFlow_User = 51,
            SignDraftPublishDraftSendtoG2GandEndFlow_UserRole = 52,
            CmsSendCopyToInitiatorUser = 53,
            CmsSendCopyToGSUser = 54,
            CmsApproveCopyAndWorkUser = 55,
            CmsSendCopyToInitiatorAndEndflowUser = 56,
            CmsSendCopyToRecieverAndEndflowUser = 57,
            CmsSendCopyUser = 58,
            CmsTransferToPOAndEndFlowUser = 59,
            InitiatorDocumentModification_User = 60,
            InitiatorDocumentModification_UserRole = 61,
            CmsTransferToRespectiveSectorAndEndflowUser = 62,
            CmsReviewDraftDocumentViceHos_User = 63,
            CmsReviewDraftDocumentViceHos_UserRole = 64,
            SignDraftPublishDraftandEndFlow_User = 65,
            SignDraftPublishDraftandEndFlow_UserRole = 66,
        }
    }
}
