using FATWA_DOMAIN.Models;
using FATWA_DOMAIN.Models.AdminModels.UserManagement;
using FATWA_DOMAIN.Models.Lms;
using FATWA_DOMAIN.Models.ViewModel;
using FATWA_DOMAIN.Models.ViewModel.Lms;

namespace FATWA_DOMAIN.Interfaces
{
    public interface ILmsLiterature
    {
        Task<List<LiteratureDetailVM>> GetLmsLiteratures();
        Task<List<LiteratureTag>> GetAllActiveLiteratureTags();
        Task<LmsLiterature> GetLiteratureDetailTagById(int Id);
        Task<int> GetNewLmsLiteratureNumber();
        Task<List<LiteratureDetailVM>> GetLmsLiteraturesAdvanceSearch(LiteratureAdvancedSearchVM advancedSearch);
        Task<List<LiteratureListMobileAppVM>> GetLmsLiteraturesForMobileApp(LiteratureAdvancedSearchVM advancedSearch);
        Task<LiteratureAllDetailsVM> GetLMSLiteratureDetailById(int LiteratureId);
        Task<List<BorrowDetailVM>> GetBorrowDetailById(int LiteratureId, string UserId, string RoleName);
        Task<List<LiteratureAllAuthorsVM>> GetLMSLiteratureAuthorsById(int LiteratureId);
        List<LmsLiterature> GetLmsLiteraturesSync();
        Task<LmsLiterature> CreateLmsLiterature(LmsLiterature LmsLiterature);
        Task<LmsLiterature> GetLiteratureDetail(int Id);
        Task<LmsLiterature> UpdateLmsLiterature(LmsLiterature LmsLiterature);
        Task SoftDeleteLmsLiterature(LmsLiterature LmsLiterature);
        Task DeleteLmsLiterature(int Id);
        Task<List<LmsLiteratureAuthor>> GetLmsLiteraturesAuthorBySearchTerm(string searchTerm);
        Task<LmsLiteratureAuthor> GetLmsLiteratureAuthorById(int authorId);
        Task<int> GetLmsLiteratureCountByAuthorId(int authorId);
        Task<List<LiteratureDetailVM>> GetLmsLiteraturesBySearchTerm(string? searchTerm, string appCulture);
        Task SoftDeleteLiterature(List<LiteratureDetailVM> literatures);

        Task<LiteratureDetailsForBorrowRequestVM> GetBarcodeNumberDetailByusingLiteratureId(int literatureId);
        Task<string> GetUserIdByEmail(string createdBy);
        Task<List<UserRole>> GetLmsAdminUser();
        Task<List<UserRole>> GetFatwaAdminUser();
        Task<bool> CheckRFIDValueExists(string barCodeNumber, string rfIdValue);
        Task<List<LmsStockTakingListVM>> GetStockTakingList(StockTakingAdvancedSearchVM advancedSearchVM);
        Task<LmsStockTakingDetailVM> GetStockTakingDetailById(Guid Id);
        Task<List<LmsStockTakingStatus>> GetStockTakingStatus();
        Task<int> GetTotalNoOfBooks();
        Task<List<LmsStockTakingBooksReportListVm>> GetLmsBookStockTakingReportList(Guid? StockTakingId);
        Task<bool> ApproveStockTakingReport(Guid StockTakingId, string ApprovedBy);
        Task<bool> SubmitStockTakingReport(SaveStockTakingVm saveStockTakingVm);
        Task<LmsStockTaking> GetAutoGeneratedReportNumber();
        Task<LmsStockTaking> GetLmsStockTakingById(Guid StockTakingId);
        Task<List<StockTakingPerformerVm>> GetPerformersByStockTakingId(Guid StockTakingId);
        Task<bool> CheckIfAnyInProgressStockTaking();
        Task<List<LmsViewableLiteratureVM>> GetLmsViewableLiteratures(LiteratureAdvancedSearchVM advancedSearch);
        Task DeleteLmsStockTaking(LmsStockTakingListVM item);
        Task<List<LmsStockTakingHistoryVm>> GetLmsStockTakingHistoryById(Guid StockTakingId);

    }
}
