//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSPRemoteSigning
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DSProfile", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class DSProfile : object
    {
        
        private DSPRemoteSigning.CertificateTokenData CertificateTokenField;
        
        private string ClientSystemNameField;
        
        private string DefaultHashAlgorithmField;
        
        private string DefaultOCSPRLField;
        
        private int DefaultPageNumberField;
        
        private DSPRemoteSigning.ReasonEntity[] DefinedReasonsField;
        
        private string DescriptionField;
        
        private bool IsLocationRequiredField;
        
        private int LOBIdField;
        
        private string NameField;
        
        private DSPRemoteSigning.ServerSignerType ServerSignerTypeField;
        
        private bool ShowDataPreviewField;
        
        private DSPRemoteSigning.SignImageData SignImageField;
        
        private DSPRemoteSigning.SigningMethod SignerMethodField;
        
        private DSPRemoteSigning.DataSignerType SignerTypeField;
        
        private DSPRemoteSigning.SignatureLevel SigningLevelField;
        
        private DSPRemoteSigning.TimeStampAuthorityData TSADataField;
        
        private DSPRemoteSigning.VerificationMethod VerifyMethodField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.CertificateTokenData CertificateToken
        {
            get
            {
                return this.CertificateTokenField;
            }
            set
            {
                this.CertificateTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientSystemName
        {
            get
            {
                return this.ClientSystemNameField;
            }
            set
            {
                this.ClientSystemNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultHashAlgorithm
        {
            get
            {
                return this.DefaultHashAlgorithmField;
            }
            set
            {
                this.DefaultHashAlgorithmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultOCSPRL
        {
            get
            {
                return this.DefaultOCSPRLField;
            }
            set
            {
                this.DefaultOCSPRLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DefaultPageNumber
        {
            get
            {
                return this.DefaultPageNumberField;
            }
            set
            {
                this.DefaultPageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.ReasonEntity[] DefinedReasons
        {
            get
            {
                return this.DefinedReasonsField;
            }
            set
            {
                this.DefinedReasonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLocationRequired
        {
            get
            {
                return this.IsLocationRequiredField;
            }
            set
            {
                this.IsLocationRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LOBId
        {
            get
            {
                return this.LOBIdField;
            }
            set
            {
                this.LOBIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.ServerSignerType ServerSignerType
        {
            get
            {
                return this.ServerSignerTypeField;
            }
            set
            {
                this.ServerSignerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowDataPreview
        {
            get
            {
                return this.ShowDataPreviewField;
            }
            set
            {
                this.ShowDataPreviewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.SignImageData SignImage
        {
            get
            {
                return this.SignImageField;
            }
            set
            {
                this.SignImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.SigningMethod SignerMethod
        {
            get
            {
                return this.SignerMethodField;
            }
            set
            {
                this.SignerMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.DataSignerType SignerType
        {
            get
            {
                return this.SignerTypeField;
            }
            set
            {
                this.SignerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.SignatureLevel SigningLevel
        {
            get
            {
                return this.SigningLevelField;
            }
            set
            {
                this.SigningLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.TimeStampAuthorityData TSAData
        {
            get
            {
                return this.TSADataField;
            }
            set
            {
                this.TSADataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.VerificationMethod VerifyMethod
        {
            get
            {
                return this.VerifyMethodField;
            }
            set
            {
                this.VerifyMethodField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificateTokenData", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class CertificateTokenData : object
    {
        
        private bool AllowSelectCertificateField;
        
        private string CertificateFilterField;
        
        private DSPRemoteSigning.TokenData[] TokenFiltersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowSelectCertificate
        {
            get
            {
                return this.AllowSelectCertificateField;
            }
            set
            {
                this.AllowSelectCertificateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateFilter
        {
            get
            {
                return this.CertificateFilterField;
            }
            set
            {
                this.CertificateFilterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.TokenData[] TokenFilters
        {
            get
            {
                return this.TokenFiltersField;
            }
            set
            {
                this.TokenFiltersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignImageData", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class SignImageData : object
    {
        
        private bool AllowImageOverrideField;
        
        private bool AllowLocationOverrideField;
        
        private bool AllowSignatureFieldOverrideField;
        
        private string CustomAttributesField;
        
        private int DefaultPageNumberField;
        
        private string DefaultSignatureFieldNameField;
        
        private DSPRemoteSigning.GeometricalData DefualtGeometryField;
        
        private byte[] GeneralImageField;
        
        private bool IsAppendLocationField;
        
        private bool IsResizableField;
        
        private DSPRemoteSigning.SignatureImageSource SourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowImageOverride
        {
            get
            {
                return this.AllowImageOverrideField;
            }
            set
            {
                this.AllowImageOverrideField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowLocationOverride
        {
            get
            {
                return this.AllowLocationOverrideField;
            }
            set
            {
                this.AllowLocationOverrideField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowSignatureFieldOverride
        {
            get
            {
                return this.AllowSignatureFieldOverrideField;
            }
            set
            {
                this.AllowSignatureFieldOverrideField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomAttributes
        {
            get
            {
                return this.CustomAttributesField;
            }
            set
            {
                this.CustomAttributesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DefaultPageNumber
        {
            get
            {
                return this.DefaultPageNumberField;
            }
            set
            {
                this.DefaultPageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultSignatureFieldName
        {
            get
            {
                return this.DefaultSignatureFieldNameField;
            }
            set
            {
                this.DefaultSignatureFieldNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.GeometricalData DefualtGeometry
        {
            get
            {
                return this.DefualtGeometryField;
            }
            set
            {
                this.DefualtGeometryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] GeneralImage
        {
            get
            {
                return this.GeneralImageField;
            }
            set
            {
                this.GeneralImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAppendLocation
        {
            get
            {
                return this.IsAppendLocationField;
            }
            set
            {
                this.IsAppendLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsResizable
        {
            get
            {
                return this.IsResizableField;
            }
            set
            {
                this.IsResizableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.SignatureImageSource Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeStampAuthorityData", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class TimeStampAuthorityData : object
    {
        
        private string EndPointField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndPoint
        {
            get
            {
                return this.EndPointField;
            }
            set
            {
                this.EndPointField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReasonEntity", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class ReasonEntity : object
    {
        
        private int IdField;
        
        private string ReasonArField;
        
        private string ReasonEnField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonAr
        {
            get
            {
                return this.ReasonArField;
            }
            set
            {
                this.ReasonArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonEn
        {
            get
            {
                return this.ReasonEnField;
            }
            set
            {
                this.ReasonEnField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerSignerType", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Enums")]
    public enum ServerSignerType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HSM = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MGOV = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PFX = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemoteUser = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KuwaitMobileID = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EStamping = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SigningMethod", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Enums")]
    public enum SigningMethod : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Client = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Server = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSignerType", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Enums")]
    public enum DataSignerType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PDF = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XADES = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureLevel", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Enums")]
    public enum SignatureLevel : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        B_B = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        B_T = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        B_LT = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        B_LTA = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XADES_B = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XADES_T = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XADES_C = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XADES_X = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XADES_XL = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerificationMethod", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Enums")]
    public enum VerificationMethod : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSelected = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OCSP = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRL = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OCSP_CRL = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenData", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class TokenData : object
    {
        
        private string CryptoProvideTypeField;
        
        private string SlotLabelField;
        
        private string TokenStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CryptoProvideType
        {
            get
            {
                return this.CryptoProvideTypeField;
            }
            set
            {
                this.CryptoProvideTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SlotLabel
        {
            get
            {
                return this.SlotLabelField;
            }
            set
            {
                this.SlotLabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenString
        {
            get
            {
                return this.TokenStringField;
            }
            set
            {
                this.TokenStringField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeometricalData", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class GeometricalData : object
    {
        
        private float HeightField;
        
        private float WidthField;
        
        private float XField;
        
        private float YField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float X
        {
            get
            {
                return this.XField;
            }
            set
            {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Y
        {
            get
            {
                return this.YField;
            }
            set
            {
                this.YField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureImageSource", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Enums")]
    public enum SignatureImageSource : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoImage = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SingleImage = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClientSystemSpecific = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCustom = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerSignerDataEntityObject", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class ServerSignerDataEntityObject : object
    {
        
        private string CertificateSubjectField;
        
        private byte[] DataField;
        
        private System.Collections.Generic.Dictionary<string, string> ExtraParametersField;
        
        private string PassCodeField;
        
        private string SignatureProfileNameField;
        
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateSubject
        {
            get
            {
                return this.CertificateSubjectField;
            }
            set
            {
                this.CertificateSubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExtraParameters
        {
            get
            {
                return this.ExtraParametersField;
            }
            set
            {
                this.ExtraParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassCode
        {
            get
            {
                return this.PassCodeField;
            }
            set
            {
                this.PassCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureProfileName
        {
            get
            {
                return this.SignatureProfileNameField;
            }
            set
            {
                this.SignatureProfileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignedDataContainer", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class SignedDataContainer : object
    {
        
        private string SelectedLocationField;
        
        private string SelectedReasonField;
        
        private DSPRemoteSigning.SignatureDetails SignDetailsField;
        
        private byte[] SignedDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedLocation
        {
            get
            {
                return this.SelectedLocationField;
            }
            set
            {
                this.SelectedLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedReason
        {
            get
            {
                return this.SelectedReasonField;
            }
            set
            {
                this.SelectedReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.SignatureDetails SignDetails
        {
            get
            {
                return this.SignDetailsField;
            }
            set
            {
                this.SignDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SignedData
        {
            get
            {
                return this.SignedDataField;
            }
            set
            {
                this.SignedDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureDetails", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPRemoteSigning.FullSignatureDetails))]
    public partial class SignatureDetails : object
    {
        
        private string IssuerNameField;
        
        private System.DateTime SignTimeField;
        
        private string SignautreLevelField;
        
        private byte[] SigningCertificateField;
        
        private string SubjectNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssuerName
        {
            get
            {
                return this.IssuerNameField;
            }
            set
            {
                this.IssuerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SignTime
        {
            get
            {
                return this.SignTimeField;
            }
            set
            {
                this.SignTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignautreLevel
        {
            get
            {
                return this.SignautreLevelField;
            }
            set
            {
                this.SignautreLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SigningCertificate
        {
            get
            {
                return this.SigningCertificateField;
            }
            set
            {
                this.SigningCertificateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectName
        {
            get
            {
                return this.SubjectNameField;
            }
            set
            {
                this.SubjectNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullSignatureDetails", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class FullSignatureDetails : DSPRemoteSigning.SignatureDetails
    {
        
        private byte[] SignedDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SignedData
        {
            get
            {
                return this.SignedDataField;
            }
            set
            {
                this.SignedDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SigningRequestBase", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPRemoteSigning.UserRemoteSigningRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPRemoteSigning.ExtendedRemoteSigningRequest))]
    public partial class SigningRequestBase : object
    {
        
        private string CertificateIssuerField;
        
        private string CertificateSubjectField;
        
        private byte[] DataField;
        
        private string DataDescriptionField;
        
        private string DataTitleField;
        
        private System.Collections.Generic.Dictionary<string, string> ExtraParametersField;
        
        private string SecurityTokenField;
        
        private string SignatureProfileNameField;
        
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateIssuer
        {
            get
            {
                return this.CertificateIssuerField;
            }
            set
            {
                this.CertificateIssuerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateSubject
        {
            get
            {
                return this.CertificateSubjectField;
            }
            set
            {
                this.CertificateSubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataDescription
        {
            get
            {
                return this.DataDescriptionField;
            }
            set
            {
                this.DataDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataTitle
        {
            get
            {
                return this.DataTitleField;
            }
            set
            {
                this.DataTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExtraParameters
        {
            get
            {
                return this.ExtraParametersField;
            }
            set
            {
                this.ExtraParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityToken
        {
            get
            {
                return this.SecurityTokenField;
            }
            set
            {
                this.SecurityTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureProfileName
        {
            get
            {
                return this.SignatureProfileNameField;
            }
            set
            {
                this.SignatureProfileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRemoteSigningRequest", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPRemoteSigning.ExtendedRemoteSigningRequest))]
    public partial class UserRemoteSigningRequest : DSPRemoteSigning.SigningRequestBase
    {
        
        private string CallbackURLField;
        
        private string ExternalIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallbackURL
        {
            get
            {
                return this.CallbackURLField;
            }
            set
            {
                this.CallbackURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId
        {
            get
            {
                return this.ExternalIdField;
            }
            set
            {
                this.ExternalIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtendedRemoteSigningRequest", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Requests")]
    public partial class ExtendedRemoteSigningRequest : DSPRemoteSigning.UserRemoteSigningRequest
    {
        
        private DSPRemoteSigning.SignatureAppearanceData SignAppearanceDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.SignatureAppearanceData SignAppearanceDetails
        {
            get
            {
                return this.SignAppearanceDetailsField;
            }
            set
            {
                this.SignAppearanceDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureAppearanceData", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class SignatureAppearanceData : object
    {
        
        private byte[] ImageDataField;
        
        private int PageNumberField;
        
        private string SelectedLocationField;
        
        private string SelectedReasonField;
        
        private DSPRemoteSigning.GeometricalData SignImageGeometryField;
        
        private string SignatureFieldNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageData
        {
            get
            {
                return this.ImageDataField;
            }
            set
            {
                this.ImageDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedLocation
        {
            get
            {
                return this.SelectedLocationField;
            }
            set
            {
                this.SelectedLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedReason
        {
            get
            {
                return this.SelectedReasonField;
            }
            set
            {
                this.SelectedReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.GeometricalData SignImageGeometry
        {
            get
            {
                return this.SignImageGeometryField;
            }
            set
            {
                this.SignImageGeometryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureFieldName
        {
            get
            {
                return this.SignatureFieldNameField;
            }
            set
            {
                this.SignatureFieldNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteResponseBase", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Responses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPRemoteSigning.StartSignResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPRemoteSigning.RemoteResultResponseBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPRemoteSigning.SignedDataContainerExt))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPRemoteSigning.RemoteSigningResponse))]
    public partial class RemoteResponseBase : object
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string ExternalRequestIdField;
        
        private string RequestIdField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalRequestId
        {
            get
            {
                return this.ExternalRequestIdField;
            }
            set
            {
                this.ExternalRequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StartSignResponse", Namespace="http://schemas.datacontract.org/2004/07/DUC.DSP.Services.Contract.RemoteSigning.E" +
        "ntities")]
    public partial class StartSignResponse : DSPRemoteSigning.RemoteResponseBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteResultResponseBase", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Responses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPRemoteSigning.SignedDataContainerExt))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPRemoteSigning.RemoteSigningResponse))]
    public partial class RemoteResultResponseBase : DSPRemoteSigning.RemoteResponseBase
    {
        
        private DSPRemoteSigning.SignedDataContainer ResultContainerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.SignedDataContainer ResultContainer
        {
            get
            {
                return this.ResultContainerField;
            }
            set
            {
                this.ResultContainerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignedDataContainerExt", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Responses")]
    public partial class SignedDataContainerExt : DSPRemoteSigning.RemoteResultResponseBase
    {
        
        private System.Collections.Generic.Dictionary<string, string> AdditionalDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteSigningResponse", Namespace="http://schemas.datacontract.org/2004/07/DUC.DSP.Services.Contract.RemoteSigning.E" +
        "ntities")]
    public partial class RemoteSigningResponse : DSPRemoteSigning.RemoteResultResponseBase
    {
        
        private System.Collections.Generic.Dictionary<string, string> AdditionalDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteStatusRequest", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Requests")]
    public partial class RemoteStatusRequest : object
    {
        
        private string ExternalRequestIdField;
        
        private string RequestIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalRequestId
        {
            get
            {
                return this.ExternalRequestIdField;
            }
            set
            {
                this.ExternalRequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteSignStatusResponseBase", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Responses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPRemoteSigning.SigningStatusResponse))]
    public partial class RemoteSignStatusResponseBase : object
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private DSPRemoteSigning.SignedDataContainerExt SignatureResultsField;
        
        private int StatusField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPRemoteSigning.SignedDataContainerExt SignatureResults
        {
            get
            {
                return this.SignatureResultsField;
            }
            set
            {
                this.SignatureResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SigningStatusResponse", Namespace="http://schemas.datacontract.org/2004/07/DUC.DSP.Services.Contract.RemoteSigning.E" +
        "ntities")]
    public partial class SigningStatusResponse : DSPRemoteSigning.RemoteSignStatusResponseBase
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://remote.dsp.diyarme.com", ConfigurationName="DSPRemoteSigning.IRemoteSigningService")]
    public interface IRemoteSigningService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/GetSigningProfile", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/GetSigningProfileResponse")]
        System.Threading.Tasks.Task<DSPRemoteSigning.DSProfile> GetSigningProfileAsync(string profileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocument", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocumentResponse")]
        System.Threading.Tasks.Task<DSPRemoteSigning.SignedDataContainer> SignDocumentAsync(DSPRemoteSigning.ServerSignerDataEntityObject signerObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocumentWithRemoteUser", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocumentWithRemoteUserRes" +
            "ponse")]
        System.Threading.Tasks.Task<DSPRemoteSigning.RemoteSigningResponse> SignDocumentWithRemoteUserAsync(DSPRemoteSigning.UserRemoteSigningRequest signerObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocumentWithRemoteUserExt" +
            "ended", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocumentWithRemoteUserExt" +
            "endedResponse")]
        System.Threading.Tasks.Task<DSPRemoteSigning.RemoteSigningResponse> SignDocumentWithRemoteUserExtendedAsync(DSPRemoteSigning.ExtendedRemoteSigningRequest signerObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/StartSignDocument", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/StartSignDocumentResponse")]
        System.Threading.Tasks.Task<DSPRemoteSigning.StartSignResponse> StartSignDocumentAsync(DSPRemoteSigning.ExtendedRemoteSigningRequest signerObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/GetSigningStatus", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/GetSigningStatusResponse")]
        System.Threading.Tasks.Task<DSPRemoteSigning.SigningStatusResponse> GetSigningStatusAsync(DSPRemoteSigning.RemoteStatusRequest signerObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/CancelSigningRequest", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/CancelSigningRequestResponse")]
        System.Threading.Tasks.Task<DSPRemoteSigning.RemoteResponseBase> CancelSigningRequestAsync(DSPRemoteSigning.RemoteStatusRequest signerObj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IRemoteSigningServiceChannel : DSPRemoteSigning.IRemoteSigningService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class RemoteSigningServiceClient : System.ServiceModel.ClientBase<DSPRemoteSigning.IRemoteSigningService>, DSPRemoteSigning.IRemoteSigningService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RemoteSigningServiceClient() : 
                base(RemoteSigningServiceClient.GetDefaultBinding(), RemoteSigningServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding_IRemoteSigningService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemoteSigningServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RemoteSigningServiceClient.GetBindingForEndpoint(endpointConfiguration), RemoteSigningServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemoteSigningServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RemoteSigningServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemoteSigningServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RemoteSigningServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemoteSigningServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<DSPRemoteSigning.DSProfile> GetSigningProfileAsync(string profileId)
        {
            return base.Channel.GetSigningProfileAsync(profileId);
        }
        
        public System.Threading.Tasks.Task<DSPRemoteSigning.SignedDataContainer> SignDocumentAsync(DSPRemoteSigning.ServerSignerDataEntityObject signerObj)
        {
            return base.Channel.SignDocumentAsync(signerObj);
        }
        
        public System.Threading.Tasks.Task<DSPRemoteSigning.RemoteSigningResponse> SignDocumentWithRemoteUserAsync(DSPRemoteSigning.UserRemoteSigningRequest signerObj)
        {
            return base.Channel.SignDocumentWithRemoteUserAsync(signerObj);
        }
        
        public System.Threading.Tasks.Task<DSPRemoteSigning.RemoteSigningResponse> SignDocumentWithRemoteUserExtendedAsync(DSPRemoteSigning.ExtendedRemoteSigningRequest signerObj)
        {
            return base.Channel.SignDocumentWithRemoteUserExtendedAsync(signerObj);
        }
        
        public System.Threading.Tasks.Task<DSPRemoteSigning.StartSignResponse> StartSignDocumentAsync(DSPRemoteSigning.ExtendedRemoteSigningRequest signerObj)
        {
            return base.Channel.StartSignDocumentAsync(signerObj);
        }
        
        public System.Threading.Tasks.Task<DSPRemoteSigning.SigningStatusResponse> GetSigningStatusAsync(DSPRemoteSigning.RemoteStatusRequest signerObj)
        {
            return base.Channel.GetSigningStatusAsync(signerObj);
        }
        
        public System.Threading.Tasks.Task<DSPRemoteSigning.RemoteResponseBase> CancelSigningRequestAsync(DSPRemoteSigning.RemoteStatusRequest signerObj)
        {
            return base.Channel.CancelSigningRequestAsync(signerObj);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IRemoteSigningService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.MessageEncoding = System.ServiceModel.WSMessageEncoding.Mtom;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IRemoteSigningService))
            {
                return new System.ServiceModel.EndpointAddress("https://fatwa.gov.kw:8855/DSPRemoteSigning/DUC.DSP.RemoteSigningService.ServiceIm" +
                        "p.RemoteSigningService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RemoteSigningServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding_IRemoteSigningService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RemoteSigningServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding_IRemoteSigningService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_IRemoteSigningService,
        }
    }
}
