using FATWA_DOMAIN.Models.AdminModels.UserManagement;
using FATWA_DOMAIN.Models.BugReporting;
using FATWA_DOMAIN.Models.CaseManagment;
using FATWA_DOMAIN.Models.ViewModel.BugReportingVMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Sockets;
using System.Text;
using System.Threading.Tasks;
//< History Author = 'Muhammad Zaeem' Date = '2024-04-28' Version = "1.0" Branch = "master" Bug Reporting Interface</History>

namespace FATWA_DOMAIN.Interfaces.BugReporting
{
    public interface IBugReporting
    {
        Task<List<BugApplication>> GetAllApplications();
        Task<List<BugModule>> GetBugModules();
        Task<List<BugModule>> GetModulesByApplicationId(int ApplicationId);
        Task<List<BugIssueType>> GetIssueTypes();
        Task<List<BugStatus>> GetBugStatuses();
        Task<List<BugSeverity>> GetSeverities();
        Task<BugTicket>GetAutoGeneratedId();
        Task CreateBugTicket(BugTicket ticket);
        Task UpdateBugTicket(BugTicket ticket);
        Task<BugTicket> GetBugTicketById(Guid TicketId);
        Task<List<TicketListVM>> GetTickets(AdvanceSearchTicketListVM advanceSearchTicketList);
        Task<TicketDetailVM> GetBugTicketDetail(Guid id);
        Task<List<TicketStatusHistoryVM>> GetTicketStatusHistory(Guid id);
        Task<ReportedBug> GetAutoGeneratedBugNumber();
        Task<ReportedBug> GetReportedBugById(Guid BugId);
        Task CreateBug(ReportedBug bug);
        Task UpdateBug(ReportedBug bug);
        Task<List<ReportedBugListVM>> GetAllReportedBug(AdvanceSearchBugListVM advanceSearchBugList);
        Task<ReportedBugDetailVM> GetReportedBugDetail(Guid Id);
        Task<List<CrashReportListVM>> GetCrashReportList(AdvanceSearchBugListVM advanceSearchBugList);
        Task<List<BugIssueTypeListVM>> GetBugIssueList();
        Task RemoveBugType(BugIssueTypeListVM issueType);
        Task SaveBugType(BugIssueType issueType);
        Task<dynamic>AddCommentFeedBack(BugCommentFeedBack bugTicketComment);
        Task UpdateCommentFeedBack(BugCommentFeedBack bugTicketComment);
        Task<List<BugTicketCommentVM>> GetBugTicketCommentFeedBack(Guid Id,int RemarksType);
        Task DeleteBugTicketComment(BugTicketCommentVM bugTicketCommentVM);
        Task AssigningTypesToUser(BugUserTypeAssignment assigningType);
        Task UnAssigningTypesToUser(BugUserTypeAssignment assigningType);
        Task UnAssigningTypesModule(BugModuleTypeAssignment assigningType);
        Task AssigningTypesModule(BugModuleTypeAssignment assigningType);
        Task<List<BugModuleTypeAssignment>> GetAssignTypeModules(int BugId);
        Task<List<BugUserTypeAssignment>> GetGroupByTypeId(int TypeId);
        Task UpdateTicketStatus(DecisionStatusVM decisionStatus);
        Task UpdateBugStatus(Guid BugId, int StatusId ,string UserName, string? Remarks);
        Task<List<ReportedBug>> GetBugList();
        Task TicketTaggingAndAssignment(TicketAssignmentVM ticketAssignment);
        Task UpdateAllSelectedTicketStatus(IList<TicketListVM> selectedTicketList, string UserName);
        Task<BugCommentFeedBack> GetBugTicketCommentById(Guid? CommentId);
        Task<List<ReportedBugListVM>> GetBugListForTagging();
        Task<List<TicketListVM>> GetTicketsListByBugId(Guid bugId);

    }
}
