//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSPExternalSigningService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SigningRequestBase", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPExternalSigningService.UserRemoteSigningRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPExternalSigningService.ExtendedRemoteSigningRequest))]
    public partial class SigningRequestBase : object
    {
        
        private string CertificateIssuerField;
        
        private string CertificateSubjectField;
        
        private byte[] DataField;
        
        private string DataDescriptionField;
        
        private string DataTitleField;
        
        private System.Collections.Generic.Dictionary<string, string> ExtraParametersField;
        
        private string SecurityTokenField;
        
        private string SignatureProfileNameField;
        
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateIssuer
        {
            get
            {
                return this.CertificateIssuerField;
            }
            set
            {
                this.CertificateIssuerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateSubject
        {
            get
            {
                return this.CertificateSubjectField;
            }
            set
            {
                this.CertificateSubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataDescription
        {
            get
            {
                return this.DataDescriptionField;
            }
            set
            {
                this.DataDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataTitle
        {
            get
            {
                return this.DataTitleField;
            }
            set
            {
                this.DataTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExtraParameters
        {
            get
            {
                return this.ExtraParametersField;
            }
            set
            {
                this.ExtraParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityToken
        {
            get
            {
                return this.SecurityTokenField;
            }
            set
            {
                this.SecurityTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureProfileName
        {
            get
            {
                return this.SignatureProfileNameField;
            }
            set
            {
                this.SignatureProfileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRemoteSigningRequest", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPExternalSigningService.ExtendedRemoteSigningRequest))]
    public partial class UserRemoteSigningRequest : DSPExternalSigningService.SigningRequestBase
    {
        
        private string CallbackURLField;
        
        private string ExternalIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallbackURL
        {
            get
            {
                return this.CallbackURLField;
            }
            set
            {
                this.CallbackURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId
        {
            get
            {
                return this.ExternalIdField;
            }
            set
            {
                this.ExternalIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtendedRemoteSigningRequest", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Requests")]
    public partial class ExtendedRemoteSigningRequest : DSPExternalSigningService.UserRemoteSigningRequest
    {
        
        private DSPExternalSigningService.SignatureAppearanceData SignAppearanceDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPExternalSigningService.SignatureAppearanceData SignAppearanceDetails
        {
            get
            {
                return this.SignAppearanceDetailsField;
            }
            set
            {
                this.SignAppearanceDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureAppearanceData", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class SignatureAppearanceData : object
    {
        
        private byte[] ImageDataField;
        
        private int PageNumberField;
        
        private string SelectedLocationField;
        
        private string SelectedReasonField;
        
        private DSPExternalSigningService.GeometricalData SignImageGeometryField;
        
        private string SignatureFieldNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageData
        {
            get
            {
                return this.ImageDataField;
            }
            set
            {
                this.ImageDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedLocation
        {
            get
            {
                return this.SelectedLocationField;
            }
            set
            {
                this.SelectedLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedReason
        {
            get
            {
                return this.SelectedReasonField;
            }
            set
            {
                this.SelectedReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPExternalSigningService.GeometricalData SignImageGeometry
        {
            get
            {
                return this.SignImageGeometryField;
            }
            set
            {
                this.SignImageGeometryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureFieldName
        {
            get
            {
                return this.SignatureFieldNameField;
            }
            set
            {
                this.SignatureFieldNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeometricalData", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class GeometricalData : object
    {
        
        private float HeightField;
        
        private float WidthField;
        
        private float XField;
        
        private float YField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float X
        {
            get
            {
                return this.XField;
            }
            set
            {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Y
        {
            get
            {
                return this.YField;
            }
            set
            {
                this.YField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteResponseBase", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Responses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPExternalSigningService.AsyncSignDataResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPExternalSigningService.RemoteResultResponseBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPExternalSigningService.SignedDataContainerExt))]
    public partial class RemoteResponseBase : object
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string ExternalRequestIdField;
        
        private string RequestIdField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalRequestId
        {
            get
            {
                return this.ExternalRequestIdField;
            }
            set
            {
                this.ExternalRequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AsyncSignDataResponse", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Services.Contract.ExternalSigningS" +
        "ervice.Entities")]
    public partial class AsyncSignDataResponse : DSPExternalSigningService.RemoteResponseBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteResultResponseBase", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Responses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPExternalSigningService.SignedDataContainerExt))]
    public partial class RemoteResultResponseBase : DSPExternalSigningService.RemoteResponseBase
    {
        
        private DSPExternalSigningService.SignedDataContainer ResultContainerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPExternalSigningService.SignedDataContainer ResultContainer
        {
            get
            {
                return this.ResultContainerField;
            }
            set
            {
                this.ResultContainerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignedDataContainerExt", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Responses")]
    public partial class SignedDataContainerExt : DSPExternalSigningService.RemoteResultResponseBase
    {
        
        private System.Collections.Generic.Dictionary<string, string> AdditionalDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignedDataContainer", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class SignedDataContainer : object
    {
        
        private string SelectedLocationField;
        
        private string SelectedReasonField;
        
        private DSPExternalSigningService.SignatureDetails SignDetailsField;
        
        private byte[] SignedDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedLocation
        {
            get
            {
                return this.SelectedLocationField;
            }
            set
            {
                this.SelectedLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedReason
        {
            get
            {
                return this.SelectedReasonField;
            }
            set
            {
                this.SelectedReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPExternalSigningService.SignatureDetails SignDetails
        {
            get
            {
                return this.SignDetailsField;
            }
            set
            {
                this.SignDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SignedData
        {
            get
            {
                return this.SignedDataField;
            }
            set
            {
                this.SignedDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureDetails", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSPExternalSigningService.FullSignatureDetails))]
    public partial class SignatureDetails : object
    {
        
        private string IssuerNameField;
        
        private System.DateTime SignTimeField;
        
        private string SignautreLevelField;
        
        private byte[] SigningCertificateField;
        
        private string SubjectNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssuerName
        {
            get
            {
                return this.IssuerNameField;
            }
            set
            {
                this.IssuerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SignTime
        {
            get
            {
                return this.SignTimeField;
            }
            set
            {
                this.SignTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignautreLevel
        {
            get
            {
                return this.SignautreLevelField;
            }
            set
            {
                this.SignautreLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SigningCertificate
        {
            get
            {
                return this.SigningCertificateField;
            }
            set
            {
                this.SigningCertificateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectName
        {
            get
            {
                return this.SubjectNameField;
            }
            set
            {
                this.SubjectNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullSignatureDetails", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class FullSignatureDetails : DSPExternalSigningService.SignatureDetails
    {
        
        private byte[] SignedDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SignedData
        {
            get
            {
                return this.SignedDataField;
            }
            set
            {
                this.SignedDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteStatusRequest", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Requests")]
    public partial class RemoteStatusRequest : object
    {
        
        private string ExternalRequestIdField;
        
        private string RequestIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalRequestId
        {
            get
            {
                return this.ExternalRequestIdField;
            }
            set
            {
                this.ExternalRequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignDocumentWithExternalUserReqStatus", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Services.Contract.ExternalSigningS" +
        "ervice.Entities")]
    public partial class SignDocumentWithExternalUserReqStatus : object
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private DSPExternalSigningService.SignedDataContainerExt SignatureResultsField;
        
        private int StatusField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSPExternalSigningService.SignedDataContainerExt SignatureResults
        {
            get
            {
                return this.SignatureResultsField;
            }
            set
            {
                this.SignatureResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://external.dsp.diyarme.com", ConfigurationName="DSPExternalSigningService.IExternalSigningService")]
    public interface IExternalSigningService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://external.dsp.diyarme.com/IExternalSigningService/SignDocumentWithExternalU" +
            "ser", ReplyAction="http://external.dsp.diyarme.com/IExternalSigningService/SignDocumentWithExternalU" +
            "serResponse")]
        System.Threading.Tasks.Task<DSPExternalSigningService.SignedDataContainerExt> SignDocumentWithExternalUserAsync(DSPExternalSigningService.ExtendedRemoteSigningRequest signerObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://external.dsp.diyarme.com/IExternalSigningService/SignDocumentWithExternalU" +
            "serAsync", ReplyAction="http://external.dsp.diyarme.com/IExternalSigningService/SignDocumentWithExternalU" +
            "serAsyncResponse")]
        System.Threading.Tasks.Task<DSPExternalSigningService.AsyncSignDataResponse> SignDocumentWithExternalUserAsyncAsync(DSPExternalSigningService.ExtendedRemoteSigningRequest signerObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://external.dsp.diyarme.com/IExternalSigningService/SignDocumentWithExternalU" +
            "serGetStatus", ReplyAction="http://external.dsp.diyarme.com/IExternalSigningService/SignDocumentWithExternalU" +
            "serGetStatusResponse")]
        System.Threading.Tasks.Task<DSPExternalSigningService.SignDocumentWithExternalUserReqStatus> SignDocumentWithExternalUserGetStatusAsync(DSPExternalSigningService.RemoteStatusRequest statusRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IExternalSigningServiceChannel : DSPExternalSigningService.IExternalSigningService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ExternalSigningServiceClient : System.ServiceModel.ClientBase<DSPExternalSigningService.IExternalSigningService>, DSPExternalSigningService.IExternalSigningService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ExternalSigningServiceClient() : 
                base(ExternalSigningServiceClient.GetDefaultBinding(), ExternalSigningServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IExternalSigningService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExternalSigningServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ExternalSigningServiceClient.GetBindingForEndpoint(endpointConfiguration), ExternalSigningServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExternalSigningServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ExternalSigningServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExternalSigningServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ExternalSigningServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExternalSigningServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<DSPExternalSigningService.SignedDataContainerExt> SignDocumentWithExternalUserAsync(DSPExternalSigningService.ExtendedRemoteSigningRequest signerObj)
        {
            return base.Channel.SignDocumentWithExternalUserAsync(signerObj);
        }
        
        public System.Threading.Tasks.Task<DSPExternalSigningService.AsyncSignDataResponse> SignDocumentWithExternalUserAsyncAsync(DSPExternalSigningService.ExtendedRemoteSigningRequest signerObj)
        {
            return base.Channel.SignDocumentWithExternalUserAsyncAsync(signerObj);
        }
        
        public System.Threading.Tasks.Task<DSPExternalSigningService.SignDocumentWithExternalUserReqStatus> SignDocumentWithExternalUserGetStatusAsync(DSPExternalSigningService.RemoteStatusRequest statusRequest)
        {
            return base.Channel.SignDocumentWithExternalUserGetStatusAsync(statusRequest);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IExternalSigningService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.MessageEncoding = System.ServiceModel.WSMessageEncoding.Mtom;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IExternalSigningService))
            {
                return new System.ServiceModel.EndpointAddress("https://fatwa.gov.kw:8855/DSPExternalSigningService/DUC.DSP.ExternalSigning.Servi" +
                        "ceImp.ExternalSigningService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ExternalSigningServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IExternalSigningService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ExternalSigningServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IExternalSigningService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IExternalSigningService,
        }
    }
}
