//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteSigningVerificationServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerificationResult", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Verification")]
    public partial class VerificationResult : object
    {
        
        private int CertificationLevelField;
        
        private string CertificationLevelDetailsField;
        
        private string OverallMessageField;
        
        private int OverallResultField;
        
        private RemoteSigningVerificationServiceReference.SignatureVerificationInfo[] SignaturesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CertificationLevel
        {
            get
            {
                return this.CertificationLevelField;
            }
            set
            {
                this.CertificationLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificationLevelDetails
        {
            get
            {
                return this.CertificationLevelDetailsField;
            }
            set
            {
                this.CertificationLevelDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OverallMessage
        {
            get
            {
                return this.OverallMessageField;
            }
            set
            {
                this.OverallMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OverallResult
        {
            get
            {
                return this.OverallResultField;
            }
            set
            {
                this.OverallResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningVerificationServiceReference.SignatureVerificationInfo[] Signatures
        {
            get
            {
                return this.SignaturesField;
            }
            set
            {
                this.SignaturesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureVerificationInfo", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Verification")]
    public partial class SignatureVerificationInfo : object
    {
        
        private string HeaderField;
        
        private bool IsLTVEnabledField;
        
        private string MessageField;
        
        private int ResultField;
        
        private bool RevisionIsValidField;
        
        private string RevisionValidityMessageField;
        
        private RemoteSigningVerificationServiceReference.VerifiedSignatureDetails SignatureDetailsField;
        
        private bool SignerCertificateIsValidField;
        
        private string SignerCertificateValidityMessageField;
        
        private int SubResultField;
        
        private string SubResultDetailsField;
        
        private RemoteSigningVerificationServiceReference.TimestampDetails TimestampDetailsField;
        
        private string VerificatoinMethodField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Header
        {
            get
            {
                return this.HeaderField;
            }
            set
            {
                this.HeaderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLTVEnabled
        {
            get
            {
                return this.IsLTVEnabledField;
            }
            set
            {
                this.IsLTVEnabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RevisionIsValid
        {
            get
            {
                return this.RevisionIsValidField;
            }
            set
            {
                this.RevisionIsValidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RevisionValidityMessage
        {
            get
            {
                return this.RevisionValidityMessageField;
            }
            set
            {
                this.RevisionValidityMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningVerificationServiceReference.VerifiedSignatureDetails SignatureDetails
        {
            get
            {
                return this.SignatureDetailsField;
            }
            set
            {
                this.SignatureDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SignerCertificateIsValid
        {
            get
            {
                return this.SignerCertificateIsValidField;
            }
            set
            {
                this.SignerCertificateIsValidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignerCertificateValidityMessage
        {
            get
            {
                return this.SignerCertificateValidityMessageField;
            }
            set
            {
                this.SignerCertificateValidityMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubResult
        {
            get
            {
                return this.SubResultField;
            }
            set
            {
                this.SubResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubResultDetails
        {
            get
            {
                return this.SubResultDetailsField;
            }
            set
            {
                this.SubResultDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningVerificationServiceReference.TimestampDetails TimestampDetails
        {
            get
            {
                return this.TimestampDetailsField;
            }
            set
            {
                this.TimestampDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerificatoinMethod
        {
            get
            {
                return this.VerificatoinMethodField;
            }
            set
            {
                this.VerificatoinMethodField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerifiedSignatureDetails", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Verification")]
    public partial class VerifiedSignatureDetails : object
    {
        
        private RemoteSigningVerificationServiceReference.ChainVerificationDetails[] ChainDetailsField;
        
        private string EmailField;
        
        private string FieldField;
        
        private string HashAlgorithmField;
        
        private string IssuerNameField;
        
        private string LevelField;
        
        private string LocationField;
        
        private string ReasonField;
        
        private int RevisionField;
        
        private System.DateTime SignTimeField;
        
        private string SignTimeMessageField;
        
        private string SignatureAlgorithmField;
        
        private byte[] SigningCertificateField;
        
        private string SubjectNameField;
        
        private string SubjectNameCNField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningVerificationServiceReference.ChainVerificationDetails[] ChainDetails
        {
            get
            {
                return this.ChainDetailsField;
            }
            set
            {
                this.ChainDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashAlgorithm
        {
            get
            {
                return this.HashAlgorithmField;
            }
            set
            {
                this.HashAlgorithmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssuerName
        {
            get
            {
                return this.IssuerNameField;
            }
            set
            {
                this.IssuerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Level
        {
            get
            {
                return this.LevelField;
            }
            set
            {
                this.LevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Revision
        {
            get
            {
                return this.RevisionField;
            }
            set
            {
                this.RevisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SignTime
        {
            get
            {
                return this.SignTimeField;
            }
            set
            {
                this.SignTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignTimeMessage
        {
            get
            {
                return this.SignTimeMessageField;
            }
            set
            {
                this.SignTimeMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureAlgorithm
        {
            get
            {
                return this.SignatureAlgorithmField;
            }
            set
            {
                this.SignatureAlgorithmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SigningCertificate
        {
            get
            {
                return this.SigningCertificateField;
            }
            set
            {
                this.SigningCertificateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectName
        {
            get
            {
                return this.SubjectNameField;
            }
            set
            {
                this.SubjectNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectNameCN
        {
            get
            {
                return this.SubjectNameCNField;
            }
            set
            {
                this.SubjectNameCNField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimestampDetails", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Verification")]
    public partial class TimestampDetails : object
    {
        
        private bool IsValidTimeStampField;
        
        private string IsValidTimeStampMessageField;
        
        private string TimeStampAuthorityField;
        
        private string TimeStampAuthorityDetilsField;
        
        private System.DateTime TimeStampDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValidTimeStamp
        {
            get
            {
                return this.IsValidTimeStampField;
            }
            set
            {
                this.IsValidTimeStampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsValidTimeStampMessage
        {
            get
            {
                return this.IsValidTimeStampMessageField;
            }
            set
            {
                this.IsValidTimeStampMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeStampAuthority
        {
            get
            {
                return this.TimeStampAuthorityField;
            }
            set
            {
                this.TimeStampAuthorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeStampAuthorityDetils
        {
            get
            {
                return this.TimeStampAuthorityDetilsField;
            }
            set
            {
                this.TimeStampAuthorityDetilsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStampDate
        {
            get
            {
                return this.TimeStampDateField;
            }
            set
            {
                this.TimeStampDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChainVerificationDetails", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Verification")]
    public partial class ChainVerificationDetails : object
    {
        
        private byte[] CertificateField;
        
        private string MessageField;
        
        private int ResultField;
        
        private int SubResultField;
        
        private string SubResultDetailsField;
        
        private string SubjectField;
        
        private string VerificatoinMethodField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Certificate
        {
            get
            {
                return this.CertificateField;
            }
            set
            {
                this.CertificateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubResult
        {
            get
            {
                return this.SubResultField;
            }
            set
            {
                this.SubResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubResultDetails
        {
            get
            {
                return this.SubResultDetailsField;
            }
            set
            {
                this.SubResultDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerificatoinMethod
        {
            get
            {
                return this.VerificatoinMethodField;
            }
            set
            {
                this.VerificatoinMethodField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteSigningVerificationServiceReference.IVerificationExtendedServicesContract")]
    public interface IVerificationExtendedServicesContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerificationExtendedServicesContract/VerifyPDFSignautre", ReplyAction="http://tempuri.org/IVerificationExtendedServicesContract/VerifyPDFSignautreRespon" +
            "se")]
        RemoteSigningVerificationServiceReference.VerifyPDFSignautreResponse VerifyPDFSignautre(RemoteSigningVerificationServiceReference.VerifyPDFSignautreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerificationExtendedServicesContract/VerifyPDFSignautre", ReplyAction="http://tempuri.org/IVerificationExtendedServicesContract/VerifyPDFSignautreRespon" +
            "se")]
        System.Threading.Tasks.Task<RemoteSigningVerificationServiceReference.VerifyPDFSignautreResponse> VerifyPDFSignautreAsync(RemoteSigningVerificationServiceReference.VerifyPDFSignautreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerificationExtendedServicesContract/VerifyXADESSignautreWith" +
            "Origianl", ReplyAction="http://tempuri.org/IVerificationExtendedServicesContract/VerifyXADESSignautreWith" +
            "OrigianlResponse")]
        RemoteSigningVerificationServiceReference.VerifyXADESSignautreWithOrigianlResponse VerifyXADESSignautreWithOrigianl(RemoteSigningVerificationServiceReference.VerifyXADESSignautreWithOrigianlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerificationExtendedServicesContract/VerifyXADESSignautreWith" +
            "Origianl", ReplyAction="http://tempuri.org/IVerificationExtendedServicesContract/VerifyXADESSignautreWith" +
            "OrigianlResponse")]
        System.Threading.Tasks.Task<RemoteSigningVerificationServiceReference.VerifyXADESSignautreWithOrigianlResponse> VerifyXADESSignautreWithOrigianlAsync(RemoteSigningVerificationServiceReference.VerifyXADESSignautreWithOrigianlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerificationExtendedServicesContract/VerifyXADESSignautre", ReplyAction="http://tempuri.org/IVerificationExtendedServicesContract/VerifyXADESSignautreResp" +
            "onse")]
        RemoteSigningVerificationServiceReference.VerifyXADESSignautreResponse VerifyXADESSignautre(RemoteSigningVerificationServiceReference.VerifyXADESSignautreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerificationExtendedServicesContract/VerifyXADESSignautre", ReplyAction="http://tempuri.org/IVerificationExtendedServicesContract/VerifyXADESSignautreResp" +
            "onse")]
        System.Threading.Tasks.Task<RemoteSigningVerificationServiceReference.VerifyXADESSignautreResponse> VerifyXADESSignautreAsync(RemoteSigningVerificationServiceReference.VerifyXADESSignautreRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyPDFSignautre", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyPDFSignautreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] pdfBytes;
        
        public VerifyPDFSignautreRequest()
        {
        }
        
        public VerifyPDFSignautreRequest(byte[] pdfBytes)
        {
            this.pdfBytes = pdfBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyPDFSignautreResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyPDFSignautreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RemoteSigningVerificationServiceReference.VerificationResult VerifyPDFSignautreResult;
        
        public VerifyPDFSignautreResponse()
        {
        }
        
        public VerifyPDFSignautreResponse(RemoteSigningVerificationServiceReference.VerificationResult VerifyPDFSignautreResult)
        {
            this.VerifyPDFSignautreResult = VerifyPDFSignautreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyXADESSignautreWithOrigianl", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyXADESSignautreWithOrigianlRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] originalData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] xadesSignature;
        
        public VerifyXADESSignautreWithOrigianlRequest()
        {
        }
        
        public VerifyXADESSignautreWithOrigianlRequest(byte[] originalData, byte[] xadesSignature)
        {
            this.originalData = originalData;
            this.xadesSignature = xadesSignature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyXADESSignautreWithOrigianlResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyXADESSignautreWithOrigianlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RemoteSigningVerificationServiceReference.VerificationResult VerifyXADESSignautreWithOrigianlResult;
        
        public VerifyXADESSignautreWithOrigianlResponse()
        {
        }
        
        public VerifyXADESSignautreWithOrigianlResponse(RemoteSigningVerificationServiceReference.VerificationResult VerifyXADESSignautreWithOrigianlResult)
        {
            this.VerifyXADESSignautreWithOrigianlResult = VerifyXADESSignautreWithOrigianlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyXADESSignautre", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyXADESSignautreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] xadesSignature;
        
        public VerifyXADESSignautreRequest()
        {
        }
        
        public VerifyXADESSignautreRequest(byte[] xadesSignature)
        {
            this.xadesSignature = xadesSignature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyXADESSignautreResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyXADESSignautreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RemoteSigningVerificationServiceReference.VerificationResult VerifyXADESSignautreResult;
        
        public VerifyXADESSignautreResponse()
        {
        }
        
        public VerifyXADESSignautreResponse(RemoteSigningVerificationServiceReference.VerificationResult VerifyXADESSignautreResult)
        {
            this.VerifyXADESSignautreResult = VerifyXADESSignautreResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IVerificationExtendedServicesContractChannel : RemoteSigningVerificationServiceReference.IVerificationExtendedServicesContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class VerificationExtendedServicesContractClient : System.ServiceModel.ClientBase<RemoteSigningVerificationServiceReference.IVerificationExtendedServicesContract>, RemoteSigningVerificationServiceReference.IVerificationExtendedServicesContract
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VerificationExtendedServicesContractClient() : 
                base(VerificationExtendedServicesContractClient.GetDefaultBinding(), VerificationExtendedServicesContractClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IVerificationExtendedServicesContract.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VerificationExtendedServicesContractClient(EndpointConfiguration endpointConfiguration) : 
                base(VerificationExtendedServicesContractClient.GetBindingForEndpoint(endpointConfiguration), VerificationExtendedServicesContractClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VerificationExtendedServicesContractClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VerificationExtendedServicesContractClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VerificationExtendedServicesContractClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VerificationExtendedServicesContractClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VerificationExtendedServicesContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public RemoteSigningVerificationServiceReference.VerifyPDFSignautreResponse VerifyPDFSignautre(RemoteSigningVerificationServiceReference.VerifyPDFSignautreRequest request)
        {
            return base.Channel.VerifyPDFSignautre(request);
        }
        
        public System.Threading.Tasks.Task<RemoteSigningVerificationServiceReference.VerifyPDFSignautreResponse> VerifyPDFSignautreAsync(RemoteSigningVerificationServiceReference.VerifyPDFSignautreRequest request)
        {
            return base.Channel.VerifyPDFSignautreAsync(request);
        }
        
        public RemoteSigningVerificationServiceReference.VerifyXADESSignautreWithOrigianlResponse VerifyXADESSignautreWithOrigianl(RemoteSigningVerificationServiceReference.VerifyXADESSignautreWithOrigianlRequest request)
        {
            return base.Channel.VerifyXADESSignautreWithOrigianl(request);
        }
        
        public System.Threading.Tasks.Task<RemoteSigningVerificationServiceReference.VerifyXADESSignautreWithOrigianlResponse> VerifyXADESSignautreWithOrigianlAsync(RemoteSigningVerificationServiceReference.VerifyXADESSignautreWithOrigianlRequest request)
        {
            return base.Channel.VerifyXADESSignautreWithOrigianlAsync(request);
        }
        
        public RemoteSigningVerificationServiceReference.VerifyXADESSignautreResponse VerifyXADESSignautre(RemoteSigningVerificationServiceReference.VerifyXADESSignautreRequest request)
        {
            return base.Channel.VerifyXADESSignautre(request);
        }
        
        public System.Threading.Tasks.Task<RemoteSigningVerificationServiceReference.VerifyXADESSignautreResponse> VerifyXADESSignautreAsync(RemoteSigningVerificationServiceReference.VerifyXADESSignautreRequest request)
        {
            return base.Channel.VerifyXADESSignautreAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVerificationExtendedServicesContract))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                result.MessageEncoding = System.ServiceModel.WSMessageEncoding.Mtom;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVerificationExtendedServicesContract))
            {
                return new System.ServiceModel.EndpointAddress("https://dspmobileservice.diyarme.com:8151/Vrf/DUC.DSP.Verification.DSPVerificatio" +
                        "nExtendedService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return VerificationExtendedServicesContractClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IVerificationExtendedServicesContract);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return VerificationExtendedServicesContractClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IVerificationExtendedServicesContract);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IVerificationExtendedServicesContract,
        }
    }
}
