//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteSigningServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DSProfile", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class DSProfile : object
    {
        
        private RemoteSigningServiceReference.CertificateTokenData CertificateTokenField;
        
        private string ClientSystemNameField;
        
        private string DefaultHashAlgorithmField;
        
        private string DefaultOCSPRLField;
        
        private int DefaultPageNumberField;
        
        private RemoteSigningServiceReference.ReasonEntity[] DefinedReasonsField;
        
        private string DescriptionField;
        
        private bool IsLocationRequiredField;
        
        private int LOBIdField;
        
        private string NameField;
        
        private RemoteSigningServiceReference.ServerSignerType ServerSignerTypeField;
        
        private bool ShowDataPreviewField;
        
        private RemoteSigningServiceReference.SignImageData SignImageField;
        
        private RemoteSigningServiceReference.SigningMethod SignerMethodField;
        
        private RemoteSigningServiceReference.DataSignerType SignerTypeField;
        
        private RemoteSigningServiceReference.SignatureLevel SigningLevelField;
        
        private RemoteSigningServiceReference.TimeStampAuthorityData TSADataField;
        
        private RemoteSigningServiceReference.VerificationMethod VerifyMethodField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.CertificateTokenData CertificateToken
        {
            get
            {
                return this.CertificateTokenField;
            }
            set
            {
                this.CertificateTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientSystemName
        {
            get
            {
                return this.ClientSystemNameField;
            }
            set
            {
                this.ClientSystemNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultHashAlgorithm
        {
            get
            {
                return this.DefaultHashAlgorithmField;
            }
            set
            {
                this.DefaultHashAlgorithmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultOCSPRL
        {
            get
            {
                return this.DefaultOCSPRLField;
            }
            set
            {
                this.DefaultOCSPRLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DefaultPageNumber
        {
            get
            {
                return this.DefaultPageNumberField;
            }
            set
            {
                this.DefaultPageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.ReasonEntity[] DefinedReasons
        {
            get
            {
                return this.DefinedReasonsField;
            }
            set
            {
                this.DefinedReasonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLocationRequired
        {
            get
            {
                return this.IsLocationRequiredField;
            }
            set
            {
                this.IsLocationRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LOBId
        {
            get
            {
                return this.LOBIdField;
            }
            set
            {
                this.LOBIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.ServerSignerType ServerSignerType
        {
            get
            {
                return this.ServerSignerTypeField;
            }
            set
            {
                this.ServerSignerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowDataPreview
        {
            get
            {
                return this.ShowDataPreviewField;
            }
            set
            {
                this.ShowDataPreviewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.SignImageData SignImage
        {
            get
            {
                return this.SignImageField;
            }
            set
            {
                this.SignImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.SigningMethod SignerMethod
        {
            get
            {
                return this.SignerMethodField;
            }
            set
            {
                this.SignerMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.DataSignerType SignerType
        {
            get
            {
                return this.SignerTypeField;
            }
            set
            {
                this.SignerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.SignatureLevel SigningLevel
        {
            get
            {
                return this.SigningLevelField;
            }
            set
            {
                this.SigningLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.TimeStampAuthorityData TSAData
        {
            get
            {
                return this.TSADataField;
            }
            set
            {
                this.TSADataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.VerificationMethod VerifyMethod
        {
            get
            {
                return this.VerifyMethodField;
            }
            set
            {
                this.VerifyMethodField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificateTokenData", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class CertificateTokenData : object
    {
        
        private bool AllowSelectCertificateField;
        
        private string CertificateFilterField;
        
        private RemoteSigningServiceReference.TokenData[] TokenFiltersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowSelectCertificate
        {
            get
            {
                return this.AllowSelectCertificateField;
            }
            set
            {
                this.AllowSelectCertificateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateFilter
        {
            get
            {
                return this.CertificateFilterField;
            }
            set
            {
                this.CertificateFilterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.TokenData[] TokenFilters
        {
            get
            {
                return this.TokenFiltersField;
            }
            set
            {
                this.TokenFiltersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignImageData", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class SignImageData : object
    {
        
        private bool AllowImageOverrideField;
        
        private bool AllowLocationOverrideField;
        
        private bool AllowSignatureFieldOverrideField;
        
        private string CustomAttributesField;
        
        private int DefaultPageNumberField;
        
        private string DefaultSignatureFieldNameField;
        
        private RemoteSigningServiceReference.GeometricalData DefualtGeometryField;
        
        private byte[] GeneralImageField;
        
        private bool IsAppendLocationField;
        
        private bool IsResizableField;
        
        private RemoteSigningServiceReference.SignatureImageSource SourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowImageOverride
        {
            get
            {
                return this.AllowImageOverrideField;
            }
            set
            {
                this.AllowImageOverrideField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowLocationOverride
        {
            get
            {
                return this.AllowLocationOverrideField;
            }
            set
            {
                this.AllowLocationOverrideField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowSignatureFieldOverride
        {
            get
            {
                return this.AllowSignatureFieldOverrideField;
            }
            set
            {
                this.AllowSignatureFieldOverrideField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomAttributes
        {
            get
            {
                return this.CustomAttributesField;
            }
            set
            {
                this.CustomAttributesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DefaultPageNumber
        {
            get
            {
                return this.DefaultPageNumberField;
            }
            set
            {
                this.DefaultPageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultSignatureFieldName
        {
            get
            {
                return this.DefaultSignatureFieldNameField;
            }
            set
            {
                this.DefaultSignatureFieldNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.GeometricalData DefualtGeometry
        {
            get
            {
                return this.DefualtGeometryField;
            }
            set
            {
                this.DefualtGeometryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] GeneralImage
        {
            get
            {
                return this.GeneralImageField;
            }
            set
            {
                this.GeneralImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAppendLocation
        {
            get
            {
                return this.IsAppendLocationField;
            }
            set
            {
                this.IsAppendLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsResizable
        {
            get
            {
                return this.IsResizableField;
            }
            set
            {
                this.IsResizableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.SignatureImageSource Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeStampAuthorityData", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class TimeStampAuthorityData : object
    {
        
        private string EndPointField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndPoint
        {
            get
            {
                return this.EndPointField;
            }
            set
            {
                this.EndPointField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReasonEntity", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class ReasonEntity : object
    {
        
        private int IdField;
        
        private string ReasonArField;
        
        private string ReasonEnField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonAr
        {
            get
            {
                return this.ReasonArField;
            }
            set
            {
                this.ReasonArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonEn
        {
            get
            {
                return this.ReasonEnField;
            }
            set
            {
                this.ReasonEnField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerSignerType", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Enums")]
    public enum ServerSignerType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HSM = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MGOV = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PFX = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemoteUser = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KuwaitMobileID = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EStamping = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SigningMethod", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Enums")]
    public enum SigningMethod : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Client = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Server = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSignerType", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Enums")]
    public enum DataSignerType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PDF = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XADES = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureLevel", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Enums")]
    public enum SignatureLevel : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        B_B = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        B_T = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        B_LT = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        B_LTA = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XADES_B = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XADES_T = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XADES_C = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XADES_X = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XADES_XL = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerificationMethod", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Enums")]
    public enum VerificationMethod : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSelected = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OCSP = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRL = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OCSP_CRL = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenData", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class TokenData : object
    {
        
        private string CryptoProvideTypeField;
        
        private string SlotLabelField;
        
        private string TokenStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CryptoProvideType
        {
            get
            {
                return this.CryptoProvideTypeField;
            }
            set
            {
                this.CryptoProvideTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SlotLabel
        {
            get
            {
                return this.SlotLabelField;
            }
            set
            {
                this.SlotLabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenString
        {
            get
            {
                return this.TokenStringField;
            }
            set
            {
                this.TokenStringField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeometricalData", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class GeometricalData : object
    {
        
        private float HeightField;
        
        private float WidthField;
        
        private float XField;
        
        private float YField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float X
        {
            get
            {
                return this.XField;
            }
            set
            {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Y
        {
            get
            {
                return this.YField;
            }
            set
            {
                this.YField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureImageSource", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Enums")]
    public enum SignatureImageSource : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoImage = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SingleImage = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClientSystemSpecific = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCustom = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerSignerDataEntityObject", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class ServerSignerDataEntityObject : object
    {
        
        private string CertificateSubjectField;
        
        private byte[] DataField;
        
        private System.Collections.Generic.Dictionary<string, string> ExtraParametersField;
        
        private string PassCodeField;
        
        private string SignatureProfileNameField;
        
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateSubject
        {
            get
            {
                return this.CertificateSubjectField;
            }
            set
            {
                this.CertificateSubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExtraParameters
        {
            get
            {
                return this.ExtraParametersField;
            }
            set
            {
                this.ExtraParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassCode
        {
            get
            {
                return this.PassCodeField;
            }
            set
            {
                this.PassCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureProfileName
        {
            get
            {
                return this.SignatureProfileNameField;
            }
            set
            {
                this.SignatureProfileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignedDataContainer", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class SignedDataContainer : object
    {
        
        private string SelectedLocationField;
        
        private string SelectedReasonField;
        
        private RemoteSigningServiceReference.SignatureDetails SignDetailsField;
        
        private byte[] SignedDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedLocation
        {
            get
            {
                return this.SelectedLocationField;
            }
            set
            {
                this.SelectedLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedReason
        {
            get
            {
                return this.SelectedReasonField;
            }
            set
            {
                this.SelectedReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.SignatureDetails SignDetails
        {
            get
            {
                return this.SignDetailsField;
            }
            set
            {
                this.SignDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SignedData
        {
            get
            {
                return this.SignedDataField;
            }
            set
            {
                this.SignedDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureDetails", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RemoteSigningServiceReference.FullSignatureDetails))]
    public partial class SignatureDetails : object
    {
        
        private string IssuerNameField;
        
        private System.DateTime SignTimeField;
        
        private string SignautreLevelField;
        
        private byte[] SigningCertificateField;
        
        private string SubjectNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssuerName
        {
            get
            {
                return this.IssuerNameField;
            }
            set
            {
                this.IssuerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SignTime
        {
            get
            {
                return this.SignTimeField;
            }
            set
            {
                this.SignTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignautreLevel
        {
            get
            {
                return this.SignautreLevelField;
            }
            set
            {
                this.SignautreLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SigningCertificate
        {
            get
            {
                return this.SigningCertificateField;
            }
            set
            {
                this.SigningCertificateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectName
        {
            get
            {
                return this.SubjectNameField;
            }
            set
            {
                this.SubjectNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullSignatureDetails", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class FullSignatureDetails : RemoteSigningServiceReference.SignatureDetails
    {
        
        private byte[] SignedDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SignedData
        {
            get
            {
                return this.SignedDataField;
            }
            set
            {
                this.SignedDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SigningRequestBase", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RemoteSigningServiceReference.UserRemoteSigningRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RemoteSigningServiceReference.ExtendedRemoteSigningRequest))]
    public partial class SigningRequestBase : object
    {
        
        private string CertificateIssuerField;
        
        private string CertificateSubjectField;
        
        private byte[] DataField;
        
        private string DataDescriptionField;
        
        private string DataTitleField;
        
        private System.Collections.Generic.Dictionary<string, string> ExtraParametersField;
        
        private string SecurityTokenField;
        
        private string SignatureProfileNameField;
        
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateIssuer
        {
            get
            {
                return this.CertificateIssuerField;
            }
            set
            {
                this.CertificateIssuerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateSubject
        {
            get
            {
                return this.CertificateSubjectField;
            }
            set
            {
                this.CertificateSubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataDescription
        {
            get
            {
                return this.DataDescriptionField;
            }
            set
            {
                this.DataDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataTitle
        {
            get
            {
                return this.DataTitleField;
            }
            set
            {
                this.DataTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExtraParameters
        {
            get
            {
                return this.ExtraParametersField;
            }
            set
            {
                this.ExtraParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityToken
        {
            get
            {
                return this.SecurityTokenField;
            }
            set
            {
                this.SecurityTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureProfileName
        {
            get
            {
                return this.SignatureProfileNameField;
            }
            set
            {
                this.SignatureProfileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRemoteSigningRequest", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RemoteSigningServiceReference.ExtendedRemoteSigningRequest))]
    public partial class UserRemoteSigningRequest : RemoteSigningServiceReference.SigningRequestBase
    {
        
        private string CallbackURLField;
        
        private string ExternalIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallbackURL
        {
            get
            {
                return this.CallbackURLField;
            }
            set
            {
                this.CallbackURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId
        {
            get
            {
                return this.ExternalIdField;
            }
            set
            {
                this.ExternalIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtendedRemoteSigningRequest", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Requests")]
    public partial class ExtendedRemoteSigningRequest : RemoteSigningServiceReference.UserRemoteSigningRequest
    {
        
        private RemoteSigningServiceReference.SignatureAppearanceData SignAppearanceDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.SignatureAppearanceData SignAppearanceDetails
        {
            get
            {
                return this.SignAppearanceDetailsField;
            }
            set
            {
                this.SignAppearanceDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureAppearanceData", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities")]
    public partial class SignatureAppearanceData : object
    {
        
        private byte[] ImageDataField;
        
        private int PageNumberField;
        
        private string SelectedLocationField;
        
        private string SelectedReasonField;
        
        private RemoteSigningServiceReference.GeometricalData SignImageGeometryField;
        
        private string SignatureFieldNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageData
        {
            get
            {
                return this.ImageDataField;
            }
            set
            {
                this.ImageDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedLocation
        {
            get
            {
                return this.SelectedLocationField;
            }
            set
            {
                this.SelectedLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedReason
        {
            get
            {
                return this.SelectedReasonField;
            }
            set
            {
                this.SelectedReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.GeometricalData SignImageGeometry
        {
            get
            {
                return this.SignImageGeometryField;
            }
            set
            {
                this.SignImageGeometryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureFieldName
        {
            get
            {
                return this.SignatureFieldNameField;
            }
            set
            {
                this.SignatureFieldNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteResponseBase", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Responses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RemoteSigningServiceReference.StartSignResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RemoteSigningServiceReference.RemoteResultResponseBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RemoteSigningServiceReference.SignedDataContainerExt))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RemoteSigningServiceReference.RemoteSigningResponse))]
    public partial class RemoteResponseBase : object
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string ExternalRequestIdField;
        
        private string RequestIdField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalRequestId
        {
            get
            {
                return this.ExternalRequestIdField;
            }
            set
            {
                this.ExternalRequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StartSignResponse", Namespace="http://schemas.datacontract.org/2004/07/DUC.DSP.Services.Contract.RemoteSigning.E" +
        "ntities")]
    public partial class StartSignResponse : RemoteSigningServiceReference.RemoteResponseBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteResultResponseBase", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Responses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RemoteSigningServiceReference.SignedDataContainerExt))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RemoteSigningServiceReference.RemoteSigningResponse))]
    public partial class RemoteResultResponseBase : RemoteSigningServiceReference.RemoteResponseBase
    {
        
        private RemoteSigningServiceReference.SignedDataContainer ResultContainerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.SignedDataContainer ResultContainer
        {
            get
            {
                return this.ResultContainerField;
            }
            set
            {
                this.ResultContainerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignedDataContainerExt", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Responses")]
    public partial class SignedDataContainerExt : RemoteSigningServiceReference.RemoteResultResponseBase
    {
        
        private System.Collections.Generic.Dictionary<string, string> AdditionalDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteSigningResponse", Namespace="http://schemas.datacontract.org/2004/07/DUC.DSP.Services.Contract.RemoteSigning.E" +
        "ntities")]
    public partial class RemoteSigningResponse : RemoteSigningServiceReference.RemoteResultResponseBase
    {
        
        private System.Collections.Generic.Dictionary<string, string> AdditionalDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteStatusRequest", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Requests")]
    public partial class RemoteStatusRequest : object
    {
        
        private string ExternalRequestIdField;
        
        private string RequestIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalRequestId
        {
            get
            {
                return this.ExternalRequestIdField;
            }
            set
            {
                this.ExternalRequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteSignStatusResponseBase", Namespace="http://schemas.datacontract.org/2004/07/DUC.DS.Shared.Entities.Responses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RemoteSigningServiceReference.SigningStatusResponse))]
    public partial class RemoteSignStatusResponseBase : object
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private RemoteSigningServiceReference.SignedDataContainerExt SignatureResultsField;
        
        private int StatusField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemoteSigningServiceReference.SignedDataContainerExt SignatureResults
        {
            get
            {
                return this.SignatureResultsField;
            }
            set
            {
                this.SignatureResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SigningStatusResponse", Namespace="http://schemas.datacontract.org/2004/07/DUC.DSP.Services.Contract.RemoteSigning.E" +
        "ntities")]
    public partial class SigningStatusResponse : RemoteSigningServiceReference.RemoteSignStatusResponseBase
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://remote.dsp.diyarme.com", ConfigurationName="RemoteSigningServiceReference.IRemoteSigningService")]
    public interface IRemoteSigningService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/GetSigningProfile", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/GetSigningProfileResponse")]
        RemoteSigningServiceReference.GetSigningProfileResponse GetSigningProfile(RemoteSigningServiceReference.GetSigningProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/GetSigningProfile", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/GetSigningProfileResponse")]
        System.Threading.Tasks.Task<RemoteSigningServiceReference.GetSigningProfileResponse> GetSigningProfileAsync(RemoteSigningServiceReference.GetSigningProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocument", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocumentResponse")]
        RemoteSigningServiceReference.SignDocumentResponse SignDocument(RemoteSigningServiceReference.SignDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocument", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocumentResponse")]
        System.Threading.Tasks.Task<RemoteSigningServiceReference.SignDocumentResponse> SignDocumentAsync(RemoteSigningServiceReference.SignDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocumentWithRemoteUser", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocumentWithRemoteUserRes" +
            "ponse")]
        RemoteSigningServiceReference.SignDocumentWithRemoteUserResponse SignDocumentWithRemoteUser(RemoteSigningServiceReference.SignDocumentWithRemoteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocumentWithRemoteUser", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocumentWithRemoteUserRes" +
            "ponse")]
        System.Threading.Tasks.Task<RemoteSigningServiceReference.SignDocumentWithRemoteUserResponse> SignDocumentWithRemoteUserAsync(RemoteSigningServiceReference.SignDocumentWithRemoteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocumentWithRemoteUserExt" +
            "ended", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocumentWithRemoteUserExt" +
            "endedResponse")]
        RemoteSigningServiceReference.SignDocumentWithRemoteUserExtendedResponse SignDocumentWithRemoteUserExtended(RemoteSigningServiceReference.SignDocumentWithRemoteUserExtendedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocumentWithRemoteUserExt" +
            "ended", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/SignDocumentWithRemoteUserExt" +
            "endedResponse")]
        System.Threading.Tasks.Task<RemoteSigningServiceReference.SignDocumentWithRemoteUserExtendedResponse> SignDocumentWithRemoteUserExtendedAsync(RemoteSigningServiceReference.SignDocumentWithRemoteUserExtendedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/StartSignDocument", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/StartSignDocumentResponse")]
        RemoteSigningServiceReference.StartSignDocumentResponse StartSignDocument(RemoteSigningServiceReference.StartSignDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/StartSignDocument", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/StartSignDocumentResponse")]
        System.Threading.Tasks.Task<RemoteSigningServiceReference.StartSignDocumentResponse> StartSignDocumentAsync(RemoteSigningServiceReference.StartSignDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/GetSigningStatus", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/GetSigningStatusResponse")]
        RemoteSigningServiceReference.GetSigningStatusResponse GetSigningStatus(RemoteSigningServiceReference.GetSigningStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/GetSigningStatus", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/GetSigningStatusResponse")]
        System.Threading.Tasks.Task<RemoteSigningServiceReference.GetSigningStatusResponse> GetSigningStatusAsync(RemoteSigningServiceReference.GetSigningStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/CancelSigningRequest", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/CancelSigningRequestResponse")]
        RemoteSigningServiceReference.CancelSigningRequestResponse CancelSigningRequest(RemoteSigningServiceReference.CancelSigningRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://remote.dsp.diyarme.com/IRemoteSigningService/CancelSigningRequest", ReplyAction="http://remote.dsp.diyarme.com/IRemoteSigningService/CancelSigningRequestResponse")]
        System.Threading.Tasks.Task<RemoteSigningServiceReference.CancelSigningRequestResponse> CancelSigningRequestAsync(RemoteSigningServiceReference.CancelSigningRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSigningProfile", WrapperNamespace="http://remote.dsp.diyarme.com", IsWrapped=true)]
    public partial class GetSigningProfileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://remote.dsp.diyarme.com", Order=0)]
        public string profileId;
        
        public GetSigningProfileRequest()
        {
        }
        
        public GetSigningProfileRequest(string profileId)
        {
            this.profileId = profileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSigningProfileResponse", WrapperNamespace="http://remote.dsp.diyarme.com", IsWrapped=true)]
    public partial class GetSigningProfileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://remote.dsp.diyarme.com", Order=0)]
        public RemoteSigningServiceReference.DSProfile GetSigningProfileResult;
        
        public GetSigningProfileResponse()
        {
        }
        
        public GetSigningProfileResponse(RemoteSigningServiceReference.DSProfile GetSigningProfileResult)
        {
            this.GetSigningProfileResult = GetSigningProfileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SignDocument", WrapperNamespace="http://remote.dsp.diyarme.com", IsWrapped=true)]
    public partial class SignDocumentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://remote.dsp.diyarme.com", Order=0)]
        public RemoteSigningServiceReference.ServerSignerDataEntityObject signerObj;
        
        public SignDocumentRequest()
        {
        }
        
        public SignDocumentRequest(RemoteSigningServiceReference.ServerSignerDataEntityObject signerObj)
        {
            this.signerObj = signerObj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SignDocumentResponse", WrapperNamespace="http://remote.dsp.diyarme.com", IsWrapped=true)]
    public partial class SignDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://remote.dsp.diyarme.com", Order=0)]
        public RemoteSigningServiceReference.SignedDataContainer SignDocumentResult;
        
        public SignDocumentResponse()
        {
        }
        
        public SignDocumentResponse(RemoteSigningServiceReference.SignedDataContainer SignDocumentResult)
        {
            this.SignDocumentResult = SignDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SignDocumentWithRemoteUser", WrapperNamespace="http://remote.dsp.diyarme.com", IsWrapped=true)]
    public partial class SignDocumentWithRemoteUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://remote.dsp.diyarme.com", Order=0)]
        public RemoteSigningServiceReference.UserRemoteSigningRequest signerObj;
        
        public SignDocumentWithRemoteUserRequest()
        {
        }
        
        public SignDocumentWithRemoteUserRequest(RemoteSigningServiceReference.UserRemoteSigningRequest signerObj)
        {
            this.signerObj = signerObj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SignDocumentWithRemoteUserResponse", WrapperNamespace="http://remote.dsp.diyarme.com", IsWrapped=true)]
    public partial class SignDocumentWithRemoteUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://remote.dsp.diyarme.com", Order=0)]
        public RemoteSigningServiceReference.RemoteSigningResponse SignDocumentWithRemoteUserResult;
        
        public SignDocumentWithRemoteUserResponse()
        {
        }
        
        public SignDocumentWithRemoteUserResponse(RemoteSigningServiceReference.RemoteSigningResponse SignDocumentWithRemoteUserResult)
        {
            this.SignDocumentWithRemoteUserResult = SignDocumentWithRemoteUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SignDocumentWithRemoteUserExtended", WrapperNamespace="http://remote.dsp.diyarme.com", IsWrapped=true)]
    public partial class SignDocumentWithRemoteUserExtendedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://remote.dsp.diyarme.com", Order=0)]
        public RemoteSigningServiceReference.ExtendedRemoteSigningRequest signerObj;
        
        public SignDocumentWithRemoteUserExtendedRequest()
        {
        }
        
        public SignDocumentWithRemoteUserExtendedRequest(RemoteSigningServiceReference.ExtendedRemoteSigningRequest signerObj)
        {
            this.signerObj = signerObj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SignDocumentWithRemoteUserExtendedResponse", WrapperNamespace="http://remote.dsp.diyarme.com", IsWrapped=true)]
    public partial class SignDocumentWithRemoteUserExtendedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://remote.dsp.diyarme.com", Order=0)]
        public RemoteSigningServiceReference.RemoteSigningResponse SignDocumentWithRemoteUserExtendedResult;
        
        public SignDocumentWithRemoteUserExtendedResponse()
        {
        }
        
        public SignDocumentWithRemoteUserExtendedResponse(RemoteSigningServiceReference.RemoteSigningResponse SignDocumentWithRemoteUserExtendedResult)
        {
            this.SignDocumentWithRemoteUserExtendedResult = SignDocumentWithRemoteUserExtendedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartSignDocument", WrapperNamespace="http://remote.dsp.diyarme.com", IsWrapped=true)]
    public partial class StartSignDocumentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://remote.dsp.diyarme.com", Order=0)]
        public RemoteSigningServiceReference.ExtendedRemoteSigningRequest signerObj;
        
        public StartSignDocumentRequest()
        {
        }
        
        public StartSignDocumentRequest(RemoteSigningServiceReference.ExtendedRemoteSigningRequest signerObj)
        {
            this.signerObj = signerObj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartSignDocumentResponse", WrapperNamespace="http://remote.dsp.diyarme.com", IsWrapped=true)]
    public partial class StartSignDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://remote.dsp.diyarme.com", Order=0)]
        public RemoteSigningServiceReference.StartSignResponse StartSignDocumentResult;
        
        public StartSignDocumentResponse()
        {
        }
        
        public StartSignDocumentResponse(RemoteSigningServiceReference.StartSignResponse StartSignDocumentResult)
        {
            this.StartSignDocumentResult = StartSignDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSigningStatus", WrapperNamespace="http://remote.dsp.diyarme.com", IsWrapped=true)]
    public partial class GetSigningStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://remote.dsp.diyarme.com", Order=0)]
        public RemoteSigningServiceReference.RemoteStatusRequest signerObj;
        
        public GetSigningStatusRequest()
        {
        }
        
        public GetSigningStatusRequest(RemoteSigningServiceReference.RemoteStatusRequest signerObj)
        {
            this.signerObj = signerObj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSigningStatusResponse", WrapperNamespace="http://remote.dsp.diyarme.com", IsWrapped=true)]
    public partial class GetSigningStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://remote.dsp.diyarme.com", Order=0)]
        public RemoteSigningServiceReference.SigningStatusResponse GetSigningStatusResult;
        
        public GetSigningStatusResponse()
        {
        }
        
        public GetSigningStatusResponse(RemoteSigningServiceReference.SigningStatusResponse GetSigningStatusResult)
        {
            this.GetSigningStatusResult = GetSigningStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelSigningRequest", WrapperNamespace="http://remote.dsp.diyarme.com", IsWrapped=true)]
    public partial class CancelSigningRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://remote.dsp.diyarme.com", Order=0)]
        public RemoteSigningServiceReference.RemoteStatusRequest signerObj;
        
        public CancelSigningRequestRequest()
        {
        }
        
        public CancelSigningRequestRequest(RemoteSigningServiceReference.RemoteStatusRequest signerObj)
        {
            this.signerObj = signerObj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelSigningRequestResponse", WrapperNamespace="http://remote.dsp.diyarme.com", IsWrapped=true)]
    public partial class CancelSigningRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://remote.dsp.diyarme.com", Order=0)]
        public RemoteSigningServiceReference.RemoteResponseBase CancelSigningRequestResult;
        
        public CancelSigningRequestResponse()
        {
        }
        
        public CancelSigningRequestResponse(RemoteSigningServiceReference.RemoteResponseBase CancelSigningRequestResult)
        {
            this.CancelSigningRequestResult = CancelSigningRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IRemoteSigningServiceChannel : RemoteSigningServiceReference.IRemoteSigningService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class RemoteSigningServiceClient : System.ServiceModel.ClientBase<RemoteSigningServiceReference.IRemoteSigningService>, RemoteSigningServiceReference.IRemoteSigningService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RemoteSigningServiceClient() : 
                base(RemoteSigningServiceClient.GetDefaultBinding(), RemoteSigningServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRemoteSigningService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemoteSigningServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RemoteSigningServiceClient.GetBindingForEndpoint(endpointConfiguration), RemoteSigningServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemoteSigningServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RemoteSigningServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemoteSigningServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RemoteSigningServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemoteSigningServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public RemoteSigningServiceReference.GetSigningProfileResponse GetSigningProfile(RemoteSigningServiceReference.GetSigningProfileRequest request)
        {
            return base.Channel.GetSigningProfile(request);
        }
        
        public System.Threading.Tasks.Task<RemoteSigningServiceReference.GetSigningProfileResponse> GetSigningProfileAsync(RemoteSigningServiceReference.GetSigningProfileRequest request)
        {
            return base.Channel.GetSigningProfileAsync(request);
        }
        
        public RemoteSigningServiceReference.SignDocumentResponse SignDocument(RemoteSigningServiceReference.SignDocumentRequest request)
        {
            return base.Channel.SignDocument(request);
        }
        
        public System.Threading.Tasks.Task<RemoteSigningServiceReference.SignDocumentResponse> SignDocumentAsync(RemoteSigningServiceReference.SignDocumentRequest request)
        {
            return base.Channel.SignDocumentAsync(request);
        }
        
        public RemoteSigningServiceReference.SignDocumentWithRemoteUserResponse SignDocumentWithRemoteUser(RemoteSigningServiceReference.SignDocumentWithRemoteUserRequest request)
        {
            return base.Channel.SignDocumentWithRemoteUser(request);
        }
        
        public System.Threading.Tasks.Task<RemoteSigningServiceReference.SignDocumentWithRemoteUserResponse> SignDocumentWithRemoteUserAsync(RemoteSigningServiceReference.SignDocumentWithRemoteUserRequest request)
        {
            return base.Channel.SignDocumentWithRemoteUserAsync(request);
        }
        
        public RemoteSigningServiceReference.SignDocumentWithRemoteUserExtendedResponse SignDocumentWithRemoteUserExtended(RemoteSigningServiceReference.SignDocumentWithRemoteUserExtendedRequest request)
        {
            return base.Channel.SignDocumentWithRemoteUserExtended(request);
        }
        
        public System.Threading.Tasks.Task<RemoteSigningServiceReference.SignDocumentWithRemoteUserExtendedResponse> SignDocumentWithRemoteUserExtendedAsync(RemoteSigningServiceReference.SignDocumentWithRemoteUserExtendedRequest request)
        {
            return base.Channel.SignDocumentWithRemoteUserExtendedAsync(request);
        }
        
        public RemoteSigningServiceReference.StartSignDocumentResponse StartSignDocument(RemoteSigningServiceReference.StartSignDocumentRequest request)
        {
            return base.Channel.StartSignDocument(request);
        }
        
        public System.Threading.Tasks.Task<RemoteSigningServiceReference.StartSignDocumentResponse> StartSignDocumentAsync(RemoteSigningServiceReference.StartSignDocumentRequest request)
        {
            return base.Channel.StartSignDocumentAsync(request);
        }
        
        public RemoteSigningServiceReference.GetSigningStatusResponse GetSigningStatus(RemoteSigningServiceReference.GetSigningStatusRequest request)
        {
            return base.Channel.GetSigningStatus(request);
        }
        
        public System.Threading.Tasks.Task<RemoteSigningServiceReference.GetSigningStatusResponse> GetSigningStatusAsync(RemoteSigningServiceReference.GetSigningStatusRequest request)
        {
            return base.Channel.GetSigningStatusAsync(request);
        }
        
        public RemoteSigningServiceReference.CancelSigningRequestResponse CancelSigningRequest(RemoteSigningServiceReference.CancelSigningRequestRequest request)
        {
            return base.Channel.CancelSigningRequest(request);
        }
        
        public System.Threading.Tasks.Task<RemoteSigningServiceReference.CancelSigningRequestResponse> CancelSigningRequestAsync(RemoteSigningServiceReference.CancelSigningRequestRequest request)
        {
            return base.Channel.CancelSigningRequestAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRemoteSigningService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRemoteSigningService))
            {
                return new System.ServiceModel.EndpointAddress("https://dspmobileservice.diyarme.com:8151/RS/DUC.DSP.RemoteSigningService.Service" +
                        "Imp.RemoteSigningService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RemoteSigningServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRemoteSigningService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RemoteSigningServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRemoteSigningService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRemoteSigningService,
        }
    }
}
