//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;

namespace G2GTarasolServiceReference
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "www.cait.gov.kw", ConfigurationName = "ServiceReference1.G2GIWSSoap")]
    public interface G2GIWSSoap
    {
        [System.ServiceModel.OperationContractAttribute(Action = "www.cait.gov.kw/G2G_SendOutGoingDocument", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<string> G2G_SendOutGoingDocument(string SenderUser, string SSite, string RSite, string Remarks, string BookNo, string G2GSubject, int SBrSiteID, int RBrSiteID, DataTable AttachmentsDT);
        
        [System.ServiceModel.OperationContractAttribute(Action = "www.cait.gov.kw/GetSitesList", ReplyAction = "*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSitesListAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "www.cait.gov.kw/GetSitesBranchList", ReplyAction = "*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSitesBranchListAsync();
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class G2GIWSSoapClient : System.ServiceModel.ClientBase<G2GTarasolServiceReference.G2GIWSSoap>, G2GTarasolServiceReference.G2GIWSSoap
    {
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public G2GIWSSoapClient(EndpointConfiguration endpointConfiguration) :
                base(G2GIWSSoapClient.GetBindingForEndpoint(endpointConfiguration), G2GIWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public System.Threading.Tasks.Task<string> G2G_SendOutGoingDocument(string SenderUser, string SSite, string RSite, string Remarks, string BookNo, string G2GSubject, int SBrSiteID, int RBrSiteID, DataTable AttachmentsDT)
        {
            return base.Channel.G2G_SendOutGoingDocument(SenderUser, SSite, RSite, Remarks, BookNo, G2GSubject, SBrSiteID, RBrSiteID, AttachmentsDT);
        }

        public System.Threading.Tasks.Task<System.Data.DataSet> GetSitesListAsync()
        {
            return base.Channel.GetSitesListAsync();
        }

        public System.Threading.Tasks.Task<System.Data.DataSet> GetSitesBranchListAsync()
        {
            return base.Channel.GetSitesBranchListAsync();
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.G2GIWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.G2GIWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://devg2g4/g2gportal/G2GIWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        public enum EndpointConfiguration
        {
            G2GIWSSoap
        }
    }
}
